l = [
  ['', 'Anguilla', ' ', 'G', ' ', 'ai-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'ai-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'ai-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'ai-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'ai-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'ai-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Antigua and Barbuda', ' ', 'G', ' ', 'ag-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'ag-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'ag-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'ag-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'ag-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'ag-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Argentina', ' ', 'ATP', ' ', 'ar-movies', ' ', 'All Audiences', ' ', 'ATP', ' ', 'ATP'],
  ['', 'SAM 13', ' ', 'ar-movies', ' ', 'Restricted to viewers over 13', ' ', 'SAM13', ' ', 'SAM 13'],
  ['', 'SAM 16', ' ', 'ar-movies', ' ', 'Restricted to viewers over 16', ' ', 'SAM16', ' ', 'SAM 16'],
  ['', 'SAM 18', ' ', 'ar-movies', ' ', 'Restricted to viewers over 18', ' ', 'SAM18', ' ', 'SAM 18'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'ar-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  ['', 'C', ' ', '✓', ' ', 'ar-movies', ' ', 'Restricted to viewers over 18', ' ', 'C', ' ', 'C'],
  ['', 'Armenia', ' ', 'G', ' ', 'am-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'am-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'am-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'am-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'am-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'am-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'չդասակարգված'],
  ['', 'Australia', ' ', 'G', ' ', 'au-o', 'fl', 'c', ' ', 'General', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'au-o', 'fl', 'c', ' ', 'Parental guidance recommended', ' ', 'PG', ' ', 'PG'],
  ['', 'M', ' ', 'au-o', 'fl', 'c', ' ', 'Recommended for mature audiences', ' ', 'M', ' ', 'M'],
  ['', 'MA15+', ' ', 'au-o', 'fl', 'c', ' ', 'Not suitable for people under the age of 15', ' ', 'MA15+', ' ', 'MA15+'],
  ['', 'R18+', ' ', 'au-o', 'fl', 'c', ' ', 'Restricted to 18 and over', ' ', 'R18+', ' ', 'R18+'],
  ['', 'X18+', ' ', '✓', ' ', 'au-o', 'fl', 'c', ' ', 'Restricted to 18 and over', ' ', 'X18+ *', ' ', 'X18+'],
  ['', 'Unrated', ' ', '✓', ' ', 'au-o', 'fl', 'c', ' ', 'Unrated', ' ', 'UR *', ' ', 'Unrated'],
  [
    '',
    'Austria',
    ' ',
    'Ab 0 Jahren',
    ' ',
    'fsk',
    ' ',
    'Approved without age restriction',
    ' ',
    '0+',
    ' ',
    'Ab 0 Jahren',
  ],
  [
    '',
    'Ab 4 Jahren',
    ' ',
    'fsk',
    '',
    'This programme is appropriate for children age 4 and',
    '',
    'above',
    ' ',
    '4+',
    ' ',
    'Ab 4 Jahren',
  ],
  ['', 'Ab 6 Jahren', ' ', 'fsk', ' ', 'Approved for age 6 and older', ' ', '6+', ' ', 'Ab 6 Jahren'],
  [
    '',
    'Ab 8 Jahren',
    ' ',
    'fsk',
    '',
    'This programme is appropriate for children age 8 and',
    '',
    'above',
    ' ',
    '8+',
    ' ',
    'Ab 8 Jahren',
  ],
  [
    '',
    'Ab 10 Jahren',
    ' ',
    'fsk',
    '',
    'This programme is appropriate for children age 10',
    '',
    'and above',
    ' ',
    '10+',
    ' ',
    'Ab 10 Jahren',
  ],
  ['', 'Ab 12 Jahren', ' ', 'fsk', ' ', 'Approved for age 12 and older', ' ', '12+', ' ', 'Ab 12 Jahren'],
  [
    '',
    'Ab 14 Jahren',
    ' ',
    'fsk',
    '',
    'This programme is appropriate for children age 14',
    '',
    'and above',
    ' ',
    '14+',
    ' ',
    'Ab 14 Jahren',
  ],
  ['', 'Ab 16 Jahren', ' ', 'fsk', ' ', 'Approved for age 16 and older', ' ', '16+', ' ', 'Ab 16 Jahren'],
  [
    '',
    'Ab 18 Jahren',
    ' ',
    'fsk',
    '',
    'Not approved for minors; approved for age 18 and',
    '',
    'older',
    ' ',
    '18+',
    ' ',
    'Ab 18 Jahren',
  ],
  [
    '',
    'Keine FSK',
    '',
    'Kennzeichnung',
    '',
    'Vorhanden',
    ' ',
    'fsk',
    ' ',
    'Unrated',
    ' ',
    'UR',
    '',
    'Keine FSK Kennzeichnung',
    '',
    'Vorhanden',
  ],
  ['', 'Azerbaijan', ' ', 'G', ' ', 'az-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'az-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'az-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'az-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'az-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  [
    '',
    'Unrated',
    ' ',
    'az-movies',
    ' ',
    'Unrated',
    ' ',
    'UR',
    '',
    'Kateqoriyası',
    '',
    'mü',
    'ə',
    'yy',
    'ə',
    'nl',
    'əş',
    'dirilm',
    'ə',
    'mi',
    'ş',
  ],
  [
    '',
    'Bahamas',
    ' ',
    'A',
    ' ',
    'bs-movies',
    ' ',
    'Suitable for universal exhibition or performance',
    ' ',
    'A',
    ' ',
    'A',
  ],
  [
    '',
    'B',
    ' ',
    'bs-movies',
    '',
    'Suitable for adults and persons under the age of 18',
    '',
    'years only when accompanied by a parent or other',
    '',
    'responsible adult',
    ' ',
    'B',
    ' ',
    'B',
  ],
  [
    '',
    'T',
    ' ',
    'bs-movies',
    '',
    'Unsuitable for persons under the age of',
    ' ',
    'fi',
    'fteen years',
    '',
    'whether accompanied by a parent or other',
    '',
    'responsible adult or not',
    ' ',
    'T',
    ' ',
    'T',
  ],
  [
    '',
    'C',
    ' ',
    'bs-movies',
    '',
    'Unsuitable for persons under the age of eighteen',
    '',
    'years whether accompanied by an adult or not',
    ' ',
    'C',
    ' ',
    'C',
  ],
  ['', 'Unrated', ' ', 'bs-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'D', ' ', '✓', ' ', 'bs-movies', ' ', 'Unsuitable for Exhibition or public performance', ' ', 'D', ' ', 'D'],
  ['', 'Bahrain', ' ', 'G', ' ', 'bh-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'bh-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'bh-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'bh-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'bh-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'bh-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Barbados', ' ', 'G', ' ', 'bb-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'bb-movies', ' ', 'Parental Guidance Suggested', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'bb-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  [
    '',
    'R',
    ' ',
    'bb-movies',
    '',
    'Restricted; for persons 18 years and older because',
    '',
    'fi',
    'lm contains strong language, nudity, sexual',
    '',
    'situations or violence',
    ' ',
    'R',
    ' ',
    'R',
  ],
  ['', 'Unrated', ' ', 'bb-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Belarus', ' ', '0', ' ', 'by-movies', ' ', 'All Ages', ' ', '0', ' ', '0'],
  ['', '*', ' ', 'by-movies', ' ', 'General Audiences', ' ', '1', ' ', '*'],
  ['', '**', ' ', 'by-movies', ' ', 'Restricted – under 16 requires a parent or guardian', ' ', '2', ' ', '**'],
  ['', '***', ' ', 'by-movies', ' ', 'No one under 16 permitted', ' ', '3', ' ', '***'],
  ['', '****', ' ', 'by-movies', ' ', 'No one under 18 permitted', ' ', '4', ' ', '****'],
  ['', '18+', ' ', '✓', ' ', 'by-movies', ' ', 'Erotic movies, no one under 18 permitted', ' ', '18+', ' ', 'Э', '18'],
  ['', 'Belgium', ' ', 'AL/G', ' ', 'be-movies', ' ', 'Suitable for all ages', ' ', 'AL-G', ' ', 'AL/G'],
  ['', '6', ' ', 'be-movies', ' ', 'Not suitable for viewers under the age of 6', ' ', '6 *', ' ', '6'],
  ['', '9', ' ', 'be-movies', ' ', 'Not suitable for viewers under the age of 9', ' ', '9 *', ' ', '9'],
  ['', '10', ' ', 'be-movies', ' ', 'Not suitable for viewers under the age of 10', ' ', '10', ' ', '10'],
  ['', '12', ' ', 'be-movies', ' ', 'Not suitable for viewers under the age of 12', ' ', '12', ' ', '12'],
  ['', '16', ' ', 'be-movies', ' ', 'Not suitable for viewers under the age of 16', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'be-movies', ' ', 'Not suitable for viewers under the age of 18', ' ', '18', ' ', '18'],
  ['', 'Non Classé', ' ', 'be-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Non Classé'],
  ['', 'Belize', ' ', 'G', ' ', 'bz-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'bz-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'bz-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'bz-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'bz-movies', ' ', 'No children under 17 admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'bz-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Bermuda', ' ', 'G', ' ', 'bm-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'bm-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'bm-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'bm-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'bm-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'bm-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Bolivia', ' ', 'TP', ' ', 'bo-movies', ' ', 'All Audiences', ' ', 'TP', ' ', 'TP'],
  ['', '14', ' ', 'bo-movies', ' ', 'Viewers older than 14 years', ' ', '14', ' ', '14'],
  ['', '18', ' ', 'bo-movies', ' ', 'Viewers older than 18 years', ' ', '18', ' ', '18'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'bo-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  ['', 'Botswana', ' ', 'G', ' ', 'bw-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'bw-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'bw-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'bw-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'bw-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'bw-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Brazil', ' ', 'L', ' ', 'br-movies', ' ', 'All Audiences', ' ', 'L', ' ', 'L'],
  ['', '10', ' ', 'br-movies', ' ', 'Not recommended for viewers under the age of 10', ' ', '10', ' ', '10'],
  ['', '12', ' ', 'br-movies', ' ', 'Not recommended for viewers under the age of 12', ' ', '12', ' ', '12'],
  ['', '14', ' ', 'br-movies', ' ', 'Not recommended for viewers under the age of 14', ' ', '14', ' ', '14'],
  ['', '16', ' ', 'br-movies', ' ', 'Not recommended for viewers under the age of 16', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'br-movies', ' ', 'Not recommended for viewers under the age of 18', ' ', '18', ' ', '18'],
  ['', 'Unrated', ' ', '✓', ' ', 'br-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'British Virgin Islands', ' ', 'G', ' ', 'vg-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'vg-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'vg-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'vg-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'vg-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'vg-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Brunei', ' ', 'U', ' ', 'bn-movies', ' ', 'Open to general audiences', ' ', 'U', ' ', 'U'],
  ['', 'A/PG', ' ', 'bn-movies', ' ', 'Children under 16 must be accompanied by an adult', ' ', 'A-PG', ' ', 'A/PG'],
  ['', 'Bulgaria', ' ', 'A', ' ', 'bg-movies', ' ', 'Recommended for children', ' ', 'A', ' ', 'A'],
  ['', 'B', ' ', 'bg-movies', ' ', 'No age restrictions', ' ', 'B', ' ', 'B'],
  ['', 'C', ' ', 'bg-movies', ' ', 'Not recommended for children under 12 years of age', ' ', 'C', ' ', 'C'],
  ['', 'D', ' ', 'bg-movies', ' ', 'Prohibited for persons under 16 years of age', ' ', 'D', ' ', 'D'],
  [
    '',
    'X',
    ' ',
    '✓',
    ' ',
    'bg-movies',
    '',
    'Забранен',
    ' ',
    'за',
    ' ',
    'лица',
    ' ',
    'под',
    ' ',
    '18-',
    'годишна',
    ' ',
    'възраст',
    '',
    '(Prohibited for persons under 18 years of age)',
    ' ',
    'X',
    ' ',
    'X',
  ],
  ['', 'Unrated', ' ', 'bg-movies', ' ', 'Unrated', ' ', 'UR *', ' ', 'Unrated'],
  ['', 'Burkina Faso', ' ', 'G', ' ', 'bf-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'bf-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'bf-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'bf-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'bf-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'bf-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Non Classé'],
  ['', 'Cambodia', ' ', 'G', ' ', 'kh-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'kh-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'kh-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'kh-movies', ' ', 'Restricted.', ' ', 'Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'R-18', ' ', 'kh-movies', ' ', 'Suitable for viewers aged 18 years or older', ' ', 'R-18', ' ', 'R-18'],
  ['', 'NC-15', ' ', 'kh-movies', ' ', 'Suitable for viewers aged 15 years or older', ' ', 'NC-15', ' ', 'NC-15'],
  ['', 'NC-17', ' ', 'kh-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Canada', ' ', 'Not Rated', ' ', 'ca-chvrs', ' ', 'Below G rating', ' ', 'NR', ' ', 'Not Rated'],
  ['', 'G', ' ', 'ca-chvrs', ' ', 'Suitable for viewing by all ages', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'ca-chvrs', ' ', 'Parental guidance advised', ' ', 'PG', ' ', 'PG'],
  ['', '14A', ' ', 'ca-chvrs', ' ', 'Not suitable for people under the age of 14', ' ', '14A', ' ', '14A'],
  ['', '18A', ' ', 'ca-chvrs', ' ', 'Not suitable for people under the age of 18', ' ', '18A', ' ', '18A'],
  ['', 'R', ' ', 'ca-chvrs', ' ', 'Restricted to 18 years and older', ' ', 'R', ' ', 'R'],
  ['', 'Unrated', ' ', 'ca-chvrs', ' ', 'Above R rating', ' ', 'UR', ' ', 'Unrated'],
  [
    '',
    'Cape Verde',
    ' ',
    'M/4',
    ' ',
    'cv-movies',
    '',
    'Movies with short duration and easy comprehension',
    '',
    'that do not cause frightening reactions',
    ' ',
    'M4',
    ' ',
    'M/4',
  ],
  ['', 'M/6', ' ', 'cv-movies', ' ', 'All movies not otherwise classi', 'fi', 'ed', ' ', 'M6', ' ', 'M/6'],
  [
    '',
    'M/12',
    ' ',
    'cv-movies',
    '',
    'Movies that, by their extension and complexity, could',
    '',
    'cause fatigue or psychological trauma to younger',
    '',
    'children',
    ' ',
    'M12',
    ' ',
    'M/12',
  ],
  [
    '',
    'M/16',
    ' ',
    'cv-movies',
    '',
    'Movies that explore excessive aspects of sexuality',
    '',
    'and/or violence',
    ' ',
    'M16',
    ' ',
    'M/16',
  ],
  ['', 'Unrated', ' ', 'cv-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sem Classi', 'fi', 'cação'],
  [
    '',
    'M/18',
    ' ',
    '✓',
    ' ',
    'cv-movies',
    '',
    'All pornography and movies that explore pathological',
    '',
    'forms of violence',
    ' ',
    'M18',
    ' ',
    'M/18',
  ],
  ['', 'Cayman Islands', ' ', 'G', ' ', 'ky-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'ky-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'ky-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'ky-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'ky-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'ky-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Chile', ' ', 'TE', ' ', 'cl-movies', ' ', 'All Audiences', ' ', 'TE', ' ', 'TE'],
  ['', 'I', ' ', 'cl-movies', ' ', 'Suitable for all children', ' ', 'I', ' ', 'I'],
  [
    '',
    'TE +7',
    ' ',
    'cl-movies',
    '',
    'All Audiences; includes images that can impact a',
    '',
    'child’s personality development & provoke confusion',
    '',
    'between reality & fantasy',
    ' ',
    'TE+7',
    ' ',
    'TE+7',
  ],
  ['', '14', ' ', 'cl-movies', ' ', 'Viewers older than 14 years', ' ', '14', ' ', '14'],
  ['', 'R', ' ', 'cl-movies', ' ', 'Viewers older than 18 years', ' ', 'R', ' ', 'R'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'cl-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  [
    '',
    'China',
    ' ',
    '无指定级',
    ' ',
    ' ',
    '中国',
    ' ',
    'cn-movies',
    ' ',
    'Unspeci',
    'fi',
    'ed - China',
    ' ',
    'CN',
    ' ',
    '无指定级',
    ' ',
    ' ',
    '中国',
  ],
  ['', 'Colombia', ' ', 'Todos', ' ', 'co-movies', ' ', 'All Audiences', ' ', 'TODOS', ' ', 'Todos'],
  ['', '7', ' ', 'co-movies', ' ', 'For viewers older than 7 years', ' ', '7', ' ', '7'],
  ['', '12', ' ', 'co-movies', ' ', 'For viewers older than 12 years', ' ', '12', ' ', '12'],
  ['', '15', ' ', 'co-movies', ' ', 'For viewers older than 15 years', ' ', '15', ' ', '15'],
  ['', '18', ' ', 'co-movies', ' ', 'For viewers older than 18 years', ' ', '18', ' ', '18'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'co-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  [
    '',
    '18x',
    ' ',
    '✓',
    ' ',
    'co-movies',
    '',
    'For viewers older than 18 years only – exhibit',
    '',
    'conditioned by sexual content',
    ' ',
    '18X',
    ' ',
    '18x',
  ],
  ['', 'Costa Rica', ' ', 'TP', ' ', 'cr-movies', ' ', 'All Audiences', ' ', 'TP', ' ', 'TP'],
  ['', 'Infantil', ' ', 'cr-movies', ' ', 'Children under the age of 12', ' ', 'I', ' ', 'Infantil'],
  ['', 'Juvenil', ' ', 'cr-movies', ' ', 'Teenagers over 12 and less than 18', ' ', 'J', ' ', 'Juvenil'],
  ['', 'Adulto', ' ', 'cr-movies', ' ', 'Adults over 18', ' ', 'A', ' ', 'Adulto'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'cr-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  ['', 'Cyprus', ' ', '(K)', ' ', 'cy-movies', ' ', 'Suitable for all', ' ', 'K', ' ', '(K)'],
  ['', '(12)', ' ', 'cy-movies', ' ', 'Unsuitable for persons under the age of 12', ' ', '12', ' ', '(12)'],
  ['', '(15)', ' ', 'cy-movies', ' ', 'Unsuitable for persons under the age of 15', ' ', '15', ' ', '(15)'],
  ['', '(18)', ' ', 'cy-movies', ' ', 'Unsuitable for persons under the age of 18', ' ', '18', ' ', '(18)'],
  ['', 'Χωρίς', '', 'Κατάταξη', ' ', 'cy-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Χωρίς', ' ', 'Κατάταξη'],
  ['', 'Czechia', ' ', 'U', ' ', 'cz-movies', ' ', 'No age limit applies', ' ', 'U', ' ', 'U'],
  ['', '12+', ' ', 'cz-movies', ' ', 'Unsuitable for persons under the age of 12', ' ', '12+', ' ', '12+'],
  ['', '15+', ' ', 'cz-movies', ' ', 'Unsuitable for persons under the age of 15', ' ', '15+', ' ', '15+'],
  ['', '18+', ' ', 'cz-movies', ' ', 'Unsuitable for persons under the age of 18', ' ', '18+', ' ', '18+'],
  ['', 'Neklasi', 'fi', 'kováno', ' ', 'cz-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Neklasi', 'fi', 'kováno'],
  ['', 'Denmark', ' ', 'A', ' ', 'dk-movies', ' ', 'Films that are allowed for all', ' ', 'A', ' ', 'A'],
  [
    '',
    '7',
    ' ',
    'dk-movies',
    '',
    'Films that are allowed for all, but not recommended',
    '',
    'children under the age of 7',
    ' ',
    '7',
    ' ',
    '7',
  ],
  ['', '11', ' ', 'dk-movies', ' ', 'Films that are allowed for children over the age of 11', ' ', '11', ' ', '11'],
  ['', '15', ' ', 'dk-movies', ' ', 'Films that are allowed for children over the age of 15', ' ', '15', ' ', '15'],
  ['', 'Ikke vurderet', ' ', '✓', ' ', 'dk-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Ikke vurderet'],
  ['', 'Dominica', ' ', 'G', ' ', 'dm-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'dm-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'dm-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'dm-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'dm-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'dm-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Dominican Republic', ' ', 'Todos', ' ', 'do-movies', ' ', 'All Audiences', ' ', 'TODOS', ' ', 'Todos'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'do-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  ['', 'Ecuador', ' ', 'TP', ' ', 'ec-movies', ' ', 'All Audiences', ' ', 'TP', ' ', 'TP'],
  ['', '12', ' ', 'ec-movies', ' ', 'Viewers older than 12 years', ' ', '12', ' ', '12'],
  ['', '15', ' ', 'ec-movies', ' ', 'Viewers older than 15 years', ' ', '15', ' ', '15'],
  [
    '',
    '18',
    ' ',
    'ec-movies',
    '',
    'Viewers older than 18 years (no one under 18 years',
    '',
    'admitted)',
    ' ',
    '18',
    ' ',
    '18',
  ],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'ec-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  ['', 'Egypt', ' ', 'G', ' ', 'eg-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'eg-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'eg-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'eg-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'eg-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'eg-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'مصنف', ' ', 'غير'],
  ['', 'El Salvador', ' ', 'A', ' ', 'sv-movies', ' ', 'For all kinds of audiences', ' ', 'A', ' ', 'A'],
  [
    '',
    '-12 con un',
    '',
    'Adulto',
    ' ',
    'sv-movies',
    ' ',
    'Menores de 12 años acompañados por un Adulto',
    ' ',
    '-12',
    ' ',
    '-12 con un Adulto',
  ],
  [
    '',
    'B',
    ' ',
    'sv-movies',
    '',
    'For audiences over 12 years (short horror or violence',
    '',
    'scenes, no sexual scenes)',
    ' ',
    'B',
    ' ',
    'B',
  ],
  [
    '',
    'C',
    ' ',
    'sv-movies',
    '',
    'for audiences over 15 years (horror and violence',
    '',
    'scenes, limited nudity, no sexual scenes)',
    ' ',
    'C',
    ' ',
    'C',
  ],
  [
    '',
    'D',
    ' ',
    'sv-movies',
    '',
    'For audiences over 18 years (horror and violence',
    '',
    'scenes, nudity and sexual scenes)',
    ' ',
    'D',
    ' ',
    'D',
  ],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'sv-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  ['', 'Estonia', ' ', 'Pere/L', ' ', 'ee-movies', ' ', 'Suitable for all', ' ', 'ALL', ' ', 'Pere/L'],
  ['', 'MS6', ' ', 'ee-movies', ' ', 'Not recommended for children under 6 years', ' ', 'MS6', ' ', 'MS6'],
  ['', 'MS12', ' ', 'ee-movies', ' ', 'Not recommended for children under 12 years', ' ', 'MS12', ' ', 'MS12'],
  ['', 'K12', ' ', 'ee-movies', ' ', 'Not permitted for children under 12 years', ' ', 'K12', ' ', 'K12'],
  ['', 'K14', ' ', 'ee-movies', ' ', 'Not permitted for children under 14 years', ' ', 'K14', ' ', 'K14'],
  ['', 'K16', ' ', 'ee-movies', ' ', 'Not permitted for children under 16 years', ' ', 'K16', ' ', 'K16'],
  ['', 'Unrated', ' ', 'ee-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'eSwatini', ' ', 'A', ' ', 'sz-movies', ' ', 'All ages', ' ', 'A', ' ', 'A'],
  [
    '',
    'PG',
    ' ',
    'sz-movies',
    '',
    'All ages but parental guidance is recommended for',
    '',
    'younger or sensitive viewers',
    ' ',
    'PG',
    ' ',
    'PG',
  ],
  ['', '10', ' ', 'sz-movies', ' ', 'Restricted to persons 10 years and older', ' ', '10', ' ', '10'],
  ['', '13', ' ', 'sz-movies', ' ', 'Restricted to persons 13 years and older', ' ', '13', ' ', '13'],
  ['', '16', ' ', 'sz-movies', ' ', 'Restricted to persons 16 years and older', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'sz-movies', ' ', 'Restricted to adults over 18 years only', ' ', '18', ' ', '18'],
  ['', 'Unrated', ' ', 'sz-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  [
    '',
    'X18',
    ' ',
    '✓',
    ' ',
    'sz-movies',
    '',
    'Restricted to adults over 18 years only; hardcore',
    '',
    'pornography',
    ' ',
    'X18',
    ' ',
    'X18',
  ],
  ['', 'Fiji', ' ', 'G', ' ', 'fj-movies', ' ', 'Approved for general exhibition', ' ', 'G', ' ', 'G'],
  [
    '',
    'Y',
    ' ',
    'fj-movies',
    '',
    'Approved for exhibition to persons over the age of',
    '',
    'thirteen years',
    ' ',
    'Y',
    ' ',
    'Y',
  ],
  [
    '',
    'A',
    ' ',
    'fj-movies',
    '',
    'Approved for exhibition to adult audiences (Adult',
    '',
    'being de',
    'fi',
    'ned as anyone over 16 years)',
    ' ',
    'A',
    ' ',
    'A',
  ],
  [
    '',
    'R',
    ' ',
    'fj-movies',
    '',
    'Approved for restricted public exhibition subject to',
    '',
    'conditions imposed by the censor',
    ' ',
    'R',
    ' ',
    'R',
  ],
  ['', 'Unrated', ' ', 'fj-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Finland', ' ', 'S/T', ' ', 'fi', '-movies', ' ', 'For all ages', ' ', 'ST', ' ', 'S/T'],
  ['', 'K-7', ' ', 'fi', '-movies', ' ', 'Not for children under 7', ' ', 'K-7', ' ', 'K-7'],
  ['', 'K-12', ' ', 'fi', '-movies', ' ', 'Not for children under 12', ' ', 'K-12', ' ', 'K-12'],
  ['', 'K-16', ' ', 'fi', '-movies', ' ', 'Not for children under 16', ' ', 'K-16', ' ', 'K-16'],
  ['', 'K-18', ' ', 'fi', '-movies', ' ', 'Only for adults', ' ', 'K-18', ' ', 'K-18'],
  ['', 'Luokittelematon', ' ', 'fi', '-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Luokittelematon'],
  ['', 'K-3', ' ', 'fi', '-movies', ' ', 'For all ages', ' ', 'K-3', ' ', 'K-3'],
  ['', 'K-11', ' ', 'fi', '-movies', ' ', 'Not for under 11 years of age', ' ', 'K-11', ' ', 'K-11'],
  ['', 'K-13', ' ', 'fi', '-movies', ' ', 'Not for under 13 years of age', ' ', 'K-13', ' ', 'K-13'],
  ['', 'K-15', ' ', 'fi', '-movies', ' ', 'Not for under 15 years of age', ' ', 'K-15', ' ', 'K-15'],
  ['', 'France', ' ', 'Tout public', ' ', 'fr-cnc', ' ', 'Suitable for all ages', ' ', 'TP', ' ', 'Tout public'],
  ['', '-10', ' ', 'fr-cnc', ' ', 'Advised against under 10 years old', ' ', '-10', ' ', '-10'],
  ['', '-12', ' ', 'fr-cnc', ' ', 'Theatrically forbidden to under 12 years old', ' ', '-12', ' ', '-12'],
  ['', '-16', ' ', 'fr-cnc', ' ', 'Theatrically forbidden to under 16 years old', ' ', '-16', ' ', '-16'],
  [
    '',
    'Sans',
    '',
    'classi',
    'fi',
    'cation',
    ' ',
    '✓',
    ' ',
    'fr-cnc',
    ' ',
    'No Rating Exists',
    ' ',
    'UR',
    ' ',
    'Sans classi',
    'fi',
    'cation',
  ],
  ['', 'Gambia', ' ', 'G', ' ', 'gm-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'gm-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'gm-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'gm-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'gm-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'gm-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  [
    '',
    'Germany',
    ' ',
    'Ab 0 Jahren',
    ' ',
    'de-fsk',
    ' ',
    'Approved without age restriction',
    ' ',
    '0+',
    ' ',
    'Ab 0 Jahren',
  ],
  ['', 'Ab 0 Jahren', ' ', 'de-fsk', ' ', 'Approved without age restriction', ' ', 'ALL *', ' ', 'Ab 0 Jahren'],
  ['', 'Ab 6 Jahren', ' ', 'de-fsk', ' ', 'Approved for age 6 and older', ' ', '6+', ' ', 'Ab 6 Jahren'],
  ['', 'Ab 12 Jahren', ' ', 'de-fsk', ' ', 'Approved for age 12 and older', ' ', '12+', ' ', 'Ab 12 Jahren'],
  ['', 'Ab 16 Jahren', ' ', 'de-fsk', ' ', 'Approved for age 16 and older', ' ', '16+', ' ', 'Ab 16 Jahren'],
  [
    '',
    'Ab 18 Jahren',
    ' ',
    'de-fsk',
    '',
    'Not approved for minors; approved for age 18 and',
    '',
    'older',
    ' ',
    '18+',
    ' ',
    'Ab 18 Jahren',
  ],
  [
    '',
    'Keine FSK',
    '',
    'Kennzeichnung',
    '',
    'Vorhanden',
    ' ',
    'de-fsk',
    ' ',
    'Unrated',
    ' ',
    'UR',
    '',
    'Keine FSK Kennzeichnung',
    '',
    'Vorhanden',
  ],
  ['', 'Ghana', ' ', 'U', ' ', 'gh-movies', ' ', 'Suitable for showing to all audiences', ' ', 'U', ' ', 'U'],
  [
    '',
    'A',
    ' ',
    'gh-movies',
    '',
    'Suitable for showing but restricted to adults and',
    '',
    'children under the age of 18 years if the children are',
    '',
    'accompanied by adults',
    ' ',
    'A',
    ' ',
    'A',
  ],
  ['', 'X', ' ', 'gh-movies', ' ', 'Suitable for showing to adults only', ' ', 'X', ' ', 'X'],
  ['', 'Unrated', ' ', 'gh-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'XX', ' ', '✓', ' ', 'gh-movies', ' ', 'Prohibited from showing on screen', ' ', 'XX', ' ', 'XX'],
  ['', 'Greece', ' ', 'K', ' ', 'gr-movies', ' ', 'Suitable for All Ages', ' ', 'K', ' ', 'K'],
  ['', '8', ' ', 'gr-movies', ' ', 'Suitable for minors over 8', ' ', '8', ' ', '8'],
  ['', '12', ' ', 'gr-movies', ' ', 'Suitable for children over 12', ' ', '12', ' ', '12'],
  ['', 'K-12', ' ', 'gr-movies', ' ', 'Suitable for minors over 12', ' ', 'K-12 *', ' ', 'K-12'],
  ['', 'K-13', ' ', 'gr-movies', ' ', 'Suitable for children over 13', ' ', 'K-13 *', ' ', 'K-13'],
  ['', 'K-15', ' ', 'gr-movies', ' ', 'Suitable for minors over 15', ' ', 'K-15 *', ' ', 'K-15'],
  ['', '16', ' ', 'gr-movies', ' ', 'Suitable for minors over 16', ' ', '16', ' ', '16'],
  ['', 'K-17', ' ', 'gr-movies', ' ', 'Suitable for adults over 17', ' ', 'K-17 *', ' ', 'K-17'],
  ['', '18+', ' ', 'gr-movies', ' ', 'Not suitable for minors', ' ', '18+', ' ', '18+'],
  ['', 'χωρίς', '', 'χαρακτηρισμό', ' ', 'gr-movies', ' ', 'Unrated', ' ', 'UR *', ' ', 'χωρίς', ' ', 'χαρακτηρισμό'],
  ['', 'Grenada', ' ', 'G', ' ', 'gd-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'gd-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'gd-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'gd-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'gd-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'gd-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Guatemala', ' ', 'A', ' ', 'gt-movies', ' ', 'All Audiences', ' ', 'A', ' ', 'A'],
  ['', 'I', ' ', 'gt-movies', ' ', 'Children', ' ', 'I', ' ', 'I'],
  ['', 'B-12', ' ', 'gt-movies', ' ', 'Viewers older than 12 years', ' ', 'B-12', ' ', 'B-12'],
  ['', 'B-15', ' ', 'gt-movies', ' ', 'Viewers older than 15 years', ' ', 'B-15', ' ', 'B-15'],
  ['', 'C', ' ', 'gt-movies', ' ', 'Viewers older than 18 years', ' ', 'C', ' ', 'C'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'gt-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  ['', 'B', ' ', 'gt-movies', ' ', 'Accompanied by an Adult', ' ', 'B', ' ', 'B'],
  ['', 'CRV', ' ', '✓', ' ', 'gt-movies', ' ', 'Extreme violence', ' ', 'CRV', ' ', 'CRV'],
  ['', 'CRX', ' ', '✓', ' ', 'gt-movies', ' ', 'Extreme pornography', ' ', 'CRX', ' ', 'CRX'],
  [
    '',
    'Guinea-Bissau',
    ' ',
    'M/4',
    ' ',
    'gw-movies',
    '',
    'Movies with short duration and easy comprehension',
    '',
    'that do not cause frightening reactions',
    ' ',
    'M4',
    ' ',
    'M/4',
  ],
  ['', 'M/6', ' ', 'gw-movies', ' ', 'All movies not otherwise classi', 'fi', 'ed', ' ', 'M6', ' ', 'M/6'],
  [
    '',
    'M/12',
    ' ',
    'gw-movies',
    '',
    'Movies that, by their extension and complexity, could',
    '',
    'cause fatigue or psychological trauma to younger',
    '',
    'children',
    ' ',
    'M12',
    ' ',
    'M/12',
  ],
  [
    '',
    'M/16',
    ' ',
    'gw-movies',
    '',
    'Movies that explore excessive aspects of sexuality',
    '',
    'and/or violence',
    ' ',
    'M16',
    ' ',
    'M/16',
  ],
  ['', 'Unrated', ' ', 'gw-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sem Classi', 'fi', 'cação'],
  [
    '',
    'M/18',
    ' ',
    '✓',
    ' ',
    'gw-movies',
    '',
    'All pornography and movies that explore pathological',
    '',
    'forms of violence',
    ' ',
    'M18',
    ' ',
    'M/18',
  ],
  ['', 'Guyana', ' ', 'All Ages', ' ', 'gy-movies', ' ', 'All Ages', ' ', 'ALL', ' ', 'All Ages'],
  ['', 'Unrated', ' ', 'gy-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Honduras', ' ', 'TP', ' ', 'hn-movies', ' ', 'All Audiences', ' ', 'TP', ' ', 'TP'],
  ['', '14', ' ', 'hn-movies', ' ', 'Viewers over 14 years', ' ', '14', ' ', '14'],
  ['', '15', ' ', 'hn-movies', ' ', 'Viewers over 15 years', ' ', '15', ' ', '15'],
  ['', '18', ' ', 'hn-movies', ' ', 'Viewers over 18 years', ' ', '18', ' ', '18'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'hn-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  ['', 'X', ' ', '✓', ' ', 'hn-movies', ' ', 'No persons under 21 admitted', ' ', 'X', ' ', 'X'],
  [
    '',
    'XX',
    ' ',
    '✓',
    ' ',
    'hn-movies',
    ' ',
    'No persons under 21 admitted, only shows at night',
    ' ',
    'XX',
    ' ',
    'XX',
  ],
  ['', 'XXX', ' ', '✓', ' ', 'hn-movies', ' ', 'Prohibited from showing in Honduras', ' ', 'XXX', ' ', 'XXX'],
  ['', 'Hong Kong', ' ', 'I', ' ', 'hk-fco', ' ', 'Suitable for all ages', ' ', 'I', ' ', 'I'],
  ['', 'IIA', ' ', 'hk-fco', ' ', 'Not suitable for children', ' ', 'IIA', ' ', 'IIA'],
  ['', 'IIB', ' ', 'hk-fco', ' ', 'Not suitable for young persons and children', ' ', 'IIB', ' ', 'IIB'],
  ['', 'III', ' ', 'hk-fco', ' ', 'For persons aged 18 and above only', ' ', 'III', ' ', 'III'],
  ['', 'UR', ' ', 'hk-fco', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', '第', 'I', '類', ' ', 'hk-movies', ' ', 'Neither obscene nor indecent', ' ', 'ALL *', ' ', '第', 'I', '類'],
  [
    '',
    '第',
    'II',
    '類',
    ' ',
    'hk-movies',
    ' ',
    'Indecent; Under 18 years prohibited',
    ' ',
    '18+ *',
    ' ',
    '第',
    'II',
    '類',
  ],
  ['', '未作評級', ' ', 'hk-movies', ' ', 'Unrated', ' ', 'UR *', ' ', '未作評級'],
  [
    '',
    'Hungary',
    ' ',
    'KN',
    ' ',
    'hu-movies',
    '',
    'Suitable for all; especially designed for children under',
    '',
    '6',
    ' ',
    'KN',
    ' ',
    'KN',
  ],
  ['', '6', ' ', 'hu-movies', ' ', 'Not recommended for audiences under the age of 6', ' ', '6', ' ', '6'],
  ['', '12', ' ', 'hu-movies', ' ', 'Not recommended for audiences under the age of 12', ' ', '12', ' ', '12'],
  ['', '16', ' ', 'hu-movies', ' ', 'Not recommended for audiences under the age of 16', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'hu-movies', ' ', 'Not recommended for audiences under the age of 18', ' ', '18', ' ', '18'],
  ['', 'Unrated', ' ', '✓', ' ', 'hu-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'India', ' ', 'U', ' ', 'in-movies', ' ', 'Unrestricted Public Exhibition', ' ', 'U', ' ', 'U'],
  [
    '',
    'UA',
    ' ',
    'in-movies',
    '',
    'Unrestricted exhibition with a statement of caution',
    '',
    'that parental discretion is required for children below',
    '',
    '12 years of age',
    ' ',
    'UA *',
    ' ',
    'UA',
  ],
  ['', 'U/A 7+', ' ', 'in-movies', ' ', 'Parental guidance for children under age 7', ' ', 'UA7+', ' ', 'U/A 7+'],
  ['', 'U/A 13+', ' ', 'in-movies', ' ', 'Parental guidance for children under age 13', ' ', 'UA13+', ' ', 'U/A 13+'],
  ['', 'U/A 16+', ' ', 'in-movies', ' ', 'Parental guidance for children under age 16', ' ', 'UA16+', ' ', 'U/A 16+'],
  ['', 'A', ' ', 'in-movies', ' ', 'Restricted to adults above the age of 18 years', ' ', 'A', ' ', 'A'],
  [
    '',
    'S',
    ' ',
    'in-movies',
    '',
    'Restricted to any special class of persons, such as',
    '',
    'doctors and scientists',
    ' ',
    'S *',
    ' ',
    'S',
  ],
  ['', 'Indonesia', ' ', 'SU', ' ', 'id-movies', ' ', 'For any age', ' ', 'SU', ' ', 'SU'],
  ['', '13', ' ', 'id-movies', ' ', 'For viewers 13 years and above', ' ', '13', ' ', '13'],
  ['', '17', ' ', 'id-movies', ' ', 'For viewers 17 years and above', ' ', '17', ' ', '17'],
  ['', '21', ' ', 'id-movies', ' ', 'For viewers 21 years and above', ' ', '21', ' ', '21'],
  ['', 'Tanpa Rating', ' ', '✓', ' ', 'id-movies', ' ', 'Unrated', ' ', 'UR *', ' ', 'Tanpa Rating'],
  ['', 'Ireland', ' ', 'G', ' ', 'ie-ifco', ' ', 'Suitable for children of school going age', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'ie-ifco', '', 'May be watched by unaccompanied children of any', '', 'age', ' ', 'PG', ' ', 'PG'],
  ['', '12', ' ', 'ie-ifco', ' ', 'Suitable for persons of 12 years and older', ' ', '12', ' ', '12'],
  ['', '15', ' ', 'ie-ifco', ' ', 'Suitable for persons of 15 years and older', ' ', '15', ' ', '15'],
  ['', '16', ' ', 'ie-ifco', ' ', 'Suitable for persons of sixteen or over', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'ie-ifco', ' ', 'Suitable for person of 18 years and older', ' ', '18', ' ', '18'],
  ['', 'Unrated', ' ', 'ie-ifco', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Israel', ' ', 'ALL', ' ', 'il-movies', ' ', 'Permitted for all', ' ', 'ALL', ' ', 'Israel'],
  ['', '12+', ' ', 'il-movies', ' ', 'Permitted for ages 12 and up', ' ', '12+', ' ', '12', ' ', 'מגיל', ' ', 'הותר'],
  ['', '14+', ' ', 'il-movies', ' ', 'Permitted for ages 14 and up', ' ', '14+', ' ', '14', ' ', 'מגיל', ' ', 'הותר'],
  ['', '16+', ' ', 'il-movies', ' ', 'Permitted for ages 16 and up', ' ', '16+', ' ', '16', ' ', 'מגיל', ' ', 'הותר'],
  ['', '18+', ' ', 'il-movies', ' ', 'Permitted for ages 18 and up', ' ', '18+', ' ', '18', ' ', 'מגיל', ' ', 'הותר'],
  ['', 'UR', ' ', 'il-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'לצפייה', ' ', 'מוגבל'],
  ['', 'Italy', ' ', 'T', ' ', 'it-movies', ' ', 'For all ages', ' ', 'T', ' ', 'T'],
  [
    '',
    'VPA',
    ' ',
    'it-movies',
    '',
    'Children should be accompanied by an adult or a',
    '',
    'responsible relative',
    ' ',
    'VPA *',
    ' ',
    'VPA',
  ],
  ['', 'VM10', ' ', 'it-movies', ' ', 'Not for under 10 years of age', ' ', 'VM10 *', ' ', 'VM10'],
  ['', 'VM12', ' ', 'it-movies', ' ', 'Not for under 12 years of age', ' ', 'VM12 *', ' ', 'VM12'],
  ['', 'VM14', ' ', 'it-movies', ' ', 'Not for under 14 years of age', ' ', 'VM14', ' ', 'VM14'],
  ['', 'VM18', ' ', 'it-movies', ' ', 'Not for under 18 years of age', ' ', 'VM18', ' ', 'VM18'],
  ['', 'Unrated', ' ', '✓', ' ', 'it-movies', ' ', 'Unrated', ' ', 'UR *', ' ', 'Unrated'],
  ['', 'Jamaica', ' ', 'U', ' ', 'jm-movies', ' ', 'Suitable for all audiences', ' ', 'U', ' ', 'U'],
  ['', 'PG', ' ', 'jm-movies', ' ', 'Parental guidance suggested', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'jm-movies',
    '',
    'Parental Guidance. Children 12 years and under must',
    '',
    'be accompanies by a parent/guardian',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  [
    '',
    'T-16',
    ' ',
    'jm-movies',
    '',
    'Adults 16 and over; No one under the age of 14',
    '',
    'admitted and children ages 14 and 15 must be',
    '',
    'accompanied by an adult',
    ' ',
    'T-16',
    ' ',
    'T-16',
  ],
  ['', 'Adult 18', ' ', 'jm-movies', ' ', 'Adults 18 and over', ' ', 'A-18', ' ', 'Adult 18'],
  ['', 'Unrated', ' ', 'jm-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Japan', ' ', 'G', ' ', 'jp-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', '12+', ' ', 'jp-movies', ' ', 'Unsuitable for children under 12', ' ', '12+', ' ', '12+'],
  ['', '15+', ' ', 'jp-movies', ' ', 'Suitable for persons of 15 years and older', ' ', '15+', ' ', '15+'],
  ['', '18+', ' ', 'jp-movies', ' ', 'Suitable for persons of 18 years and older', ' ', '18+', ' ', '18+'],
  ['', 'UR', ' ', 'jp-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'G', ' ', 'jp-eirin', ' ', 'General Audiences', ' ', 'G *', ' ', 'G'],
  [
    '',
    'PG12',
    ' ',
    'jp-eirin',
    '',
    'Some material may be unsuitable for children under',
    '',
    '12. Accompanying parent or adult guardian is',
    '',
    'desirable',
    ' ',
    'PG12 *',
    ' ',
    'PG12',
  ],
  [
    '',
    'R15+',
    ' ',
    'jp-eirin',
    '',
    'Restricted to mature audiences 15 years and over. No',
    '',
    'one younger than 15 admitted',
    ' ',
    'R15+ *',
    ' ',
    'R15+',
  ],
  [
    '',
    'R18+',
    ' ',
    'jp-eirin',
    '',
    'Restricted to adults 18 years and over. No one',
    '',
    'younger than 18 admitted',
    ' ',
    'R18+ *',
    ' ',
    'R18+',
  ],
  ['', '未審査', ' ', 'jp-eirin', ' ', 'Unrated', ' ', 'UR *', ' ', '未審査'],
  ['', 'Jordan', ' ', 'G', ' ', 'jo-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'jo-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'jo-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'jo-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'jo-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'jo-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Kazakhstan', ' ', 'K', ' ', 'kz-movies', ' ', 'All ages', ' ', 'ALL', ' ', 'K'],
  ['', 'БА', ' ', 'kz-movies', ' ', 'For 12 years and under', ' ', '12', ' ', 'БА'],
  [
    '',
    'Б',
    '14',
    ' ',
    'kz-movies',
    '',
    'Parental guidance recommended for children under',
    '',
    '14',
    ' ',
    '14',
    ' ',
    'Б',
    '14',
  ],
  [
    '',
    'Е',
    '16',
    ' ',
    'kz-movies',
    '',
    'Parental guidance recommended for children under',
    '',
    '16',
    ' ',
    '16',
    ' ',
    'Е',
    '16',
  ],
  ['', 'Е', '18', ' ', 'kz-movies', ' ', 'For 18 years and above', ' ', '18', ' ', 'Е', '18'],
  ['', 'НА', ' ', '✓', ' ', 'kz-movies', ' ', 'For 21 years and above only', ' ', 'HA *', ' ', 'НА'],
  ['', 'Kenya', ' ', 'GE', ' ', 'ke-movies', ' ', 'General Exhibition', ' ', 'GE', ' ', 'GE'],
  ['', 'PG', ' ', 'ke-movies', ' ', 'Parental Guidance Recommended', ' ', 'PG', ' ', 'PG'],
  ['', '16', ' ', 'ke-movies', ' ', 'Not Suitable for persons under 16 years', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'ke-movies', ' ', 'Restricted to persons aged 18 and above', ' ', '18', ' ', '18'],
  ['', 'Unrated', ' ', '✓', ' ', 'ke-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Korea', ' ', 'kr-movies', ' ', 'All ages', ' ', 'ALL'],
  ['', '12', ' ', 'kr-movies', ' ', '12 years or older', ' ', '12', ' ', '12'],
  ['', '15', ' ', 'kr-movies', ' ', '15 years or older', ' ', '15', ' ', '15'],
  ['', '18', ' ', 'kr-movies', ' ', 'May not be viewed by youth under 18 years', ' ', '18'],
  ['', 'Kyrgyzstan', ' ', 'Л', ' ', 'kg-movies', ' ', 'General audiences', ' ', 'ALL', ' ', 'Л'],
  ['', 'Д', ' ', 'kg-movies', ' ', 'Children’s audiences', ' ', 'C', ' ', 'Д'],
  ['', 'Д', '+', ' ', 'kg-movies', ' ', 'Children under 16 years are not permitted', ' ', '16+', ' ', 'Д', '+'],
  ['', 'С', ' ', 'kg-movies', ' ', 'Individuals under 18 years are not permitted', ' ', '18+', ' ', 'С'],
  ['', 'классификацияс', '', 'ыз', ' ', 'kg-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'классификациясыз'],
  ['', 'Laos', ' ', 'G', ' ', 'la-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'la-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'la-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'la-movies', ' ', 'Restricted.', ' ', 'Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'la-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'la-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  [
    '',
    'Latvia',
    ' ',
    'U',
    ' ',
    'lv-movies',
    ' ',
    'For universal audience - suitable for all age groups',
    ' ',
    'U',
    ' ',
    'U',
  ],
  ['', '7+', ' ', 'lv-movies', ' ', 'Suitable for persons of at least 7 years of age', ' ', '7+', ' ', '7+'],
  ['', '12+', ' ', 'lv-movies', ' ', 'Suitable for persons of at least 12 years of age', ' ', '12+', ' ', '12+'],
  ['', '16+', ' ', 'lv-movies', ' ', 'Suitable for persons of at least 16 years of age', ' ', '16+', ' ', '16+'],
  ['', '18+', ' ', 'lv-movies', ' ', 'Suitable for persons of at least 18 years of age', ' ', '18+', ' ', '18+'],
  ['', 'Unrated', ' ', '✓', ' ', 'lv-movies', ' ', 'Unrated', ' ', 'UR *', ' ', 'Unrated'],
  ['', 'Lebanon', ' ', 'GA', ' ', 'lb-movies', ' ', 'General Audience', ' ', 'GA', ' ', 'GA'],
  ['', '12', ' ', 'lb-movies', ' ', 'Forbidden for those who are less than 12 years old', ' ', '12', ' ', '12'],
  ['', '15', ' ', 'lb-movies', ' ', 'Forbidden for those who are less than 15 years old', ' ', '15', ' ', '15'],
  ['', '18', ' ', 'lb-movies', ' ', 'Forbidden for those who are less than 18 years old', ' ', '18', ' ', '18'],
  ['', 'Unrated', ' ', 'lb-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'مصنف', ' ', 'غير'],
  ['', 'Lithuania', ' ', 'V', ' ', 'lt-movies', ' ', 'For viewers of all ages', ' ', 'V', ' ', 'V'],
  ['', 'N-7', ' ', 'lt-movies', ' ', 'For viewers over the age of 7', ' ', 'N-7', ' ', 'N-7'],
  ['', 'N-13', ' ', 'lt-movies', ' ', 'For viewers over the age of 13', ' ', 'N-13', ' ', 'N-13'],
  ['', 'N-16', ' ', 'lt-movies', ' ', 'For viewers over the age of 16', ' ', 'N-16', ' ', 'N-16'],
  ['', 'N-18', ' ', 'lt-movies', ' ', 'For viewers over the age of 18', ' ', 'N-18', ' ', 'N-18'],
  [
    '',
    'T',
    ' ',
    'lt-movies',
    '',
    'Recommended that viewers under the age of 16 view',
    '',
    'with parents or guardians',
    ' ',
    'T',
    ' ',
    'T',
  ],
  ['', 'Unrated', ' ', '✓', ' ', 'lt-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Luxembourg', ' ', 'AL/G', ' ', 'lu-movies', ' ', 'Suitable for all ages', ' ', 'AL-G', ' ', 'AL/G'],
  ['', '6', ' ', 'lu-movies', ' ', 'Not suitable for viewers under the age of 6', ' ', '6', ' ', '6'],
  ['', '9', ' ', 'lu-movies', ' ', 'Not suitable for viewers under the age of 9', ' ', '9', ' ', '9'],
  ['', '10', ' ', 'lu-movies', ' ', 'Not suitable for viewers under the age of 10', ' ', '10', ' ', '10'],
  ['', '12', ' ', 'lu-movies', ' ', 'Not suitable for viewers under the age of 12', ' ', '12', ' ', '12'],
  ['', '16', ' ', 'lu-movies', ' ', 'Not suitable for viewers under the age of 16', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'lu-movies', ' ', 'Not suitable for viewers under the age of 18', ' ', '18', ' ', '18'],
  ['', 'Non Classé', ' ', 'lu-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Non Classé'],
  ['', 'Macau', ' ', 'A', ' ', 'mo-movies', ' ', 'For all ages', ' ', 'A', ' ', 'A'],
  ['', 'B', ' ', 'mo-movies', ' ', 'Not advisable for 13 years old and under', ' ', 'B', ' ', 'B'],
  [
    '',
    'C',
    ' ',
    'mo-movies',
    '',
    'Not advisable for 18 years old and under, and',
    '',
    'forbidden for 13 years old and under',
    ' ',
    'C',
    ' ',
    'C',
  ],
  ['', 'D', ' ', 'mo-movies', ' ', 'Forbidden for 18 years old and under', ' ', 'D', ' ', 'D'],
  ['', 'Unrated', ' ', 'mo-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Malaysia', ' ', 'U', ' ', 'my-movies', ' ', 'Suitable for all audiences', ' ', 'U', ' ', 'U'],
  [
    '',
    'PG-13',
    ' ',
    'my-movies',
    '',
    'Suitable for viewing by those aged 13 years and',
    '',
    'above',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  [
    '',
    '18',
    ' ',
    'my-movies',
    '',
    'Suitable for viewing by those aged 18 years and',
    '',
    'above',
    ' ',
    '18',
    ' ',
    '18',
  ],
  ['', 'Belum Ditapis', ' ', 'my-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Belum Ditapis'],
  ['', 'Malta', ' ', 'U', ' ', 'mt-movies', ' ', 'Suitable for all', ' ', 'U', ' ', 'U'],
  [
    '',
    'PG',
    ' ',
    'mt-movies',
    '',
    'Parental guidance. Some scenes are unsuitable for',
    '',
    'young children and the guidance of parents or',
    '',
    'guardians is deemed necessary',
    ' ',
    'PG',
    ' ',
    'PG',
  ],
  ['', '12', ' ', 'mt-movies', ' ', 'Suitable only for persons of twelve years and over', ' ', '12', ' ', '12'],
  ['', '14', ' ', 'mt-movies', ' ', 'Suitable only for persons of fourteen years and over', ' ', '14', ' ', '14'],
  ['', '16', ' ', 'mt-movies', ' ', 'Suitable only for persons of sixteen years and over', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'mt-movies', ' ', 'Suitable only for persons of eighteen years and over', ' ', '18', ' ', '18'],
  ['', 'Unrated', ' ', 'mt-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Mauritius', ' ', 'U', ' ', 'mu-movies', ' ', 'Suitable for all audiences (Universal)', ' ', 'U', ' ', 'U'],
  [
    '',
    'PG',
    ' ',
    'mu-movies',
    '',
    'Parental Guidance is compulsory for children under',
    '',
    'the age of 12',
    ' ',
    'PG',
    ' ',
    'PG',
  ],
  ['', '15', ' ', 'mu-movies', ' ', 'Suitable for audiences 15 and over', ' ', '15', ' ', '15'],
  ['', '18', ' ', 'mu-movies', ' ', 'Suitable for audiences 18 and over', ' ', '18', ' ', '18'],
  ['', 'Unrated', ' ', 'mu-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  [
    '',
    '18R',
    ' ',
    '✓',
    ' ',
    'mu-movies',
    '',
    'No one under 18 admitted; subject to speci',
    'fi',
    'ed',
    '',
    'conditions',
    ' ',
    '18R',
    ' ',
    '18R',
  ],
  ['', 'Mexico', ' ', 'AA', ' ', 'mx-movies', ' ', 'Acceptable for children under 7 years', ' ', 'AA', ' ', 'AA'],
  ['', 'A', ' ', 'mx-movies', ' ', 'All Audiences', ' ', 'A', ' ', 'A'],
  ['', 'B', ' ', 'mx-movies', ' ', 'For adolescents of 12 years or older', ' ', 'B', ' ', 'B'],
  [
    '',
    'B-15',
    ' ',
    'mx-movies',
    '',
    'B movies not recommended for adolescents under 15',
    '',
    'years',
    ' ',
    'B-15',
    ' ',
    'B-15',
  ],
  ['', 'C', ' ', 'mx-movies', ' ', 'For adults 18 years or older', ' ', 'C', ' ', 'C'],
  ['', 'Unrated', ' ', '✓', ' ', 'mx-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Micronesia', ' ', 'G', ' ', 'fm-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'fm-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'fm-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'fm-movies', ' ', 'Restricted.', ' ', 'Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'fm-movies', ' ', 'No children under 17 admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'fm-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  [
    '',
    'Moldova',
    '',
    'Pentru toate',
    '',
    'vârstele',
    ' ',
    'md-movies',
    ' ',
    'All ages',
    ' ',
    'ALL',
    ' ',
    'Pentru toate vârstele',
  ],
  ['', 'AP', ' ', 'md-movies', ' ', 'With parental consent only', ' ', 'AP', ' ', 'AP'],
  ['', '12', ' ', 'md-movies', ' ', 'No one under 12 years permitted', ' ', '12', ' ', '12'],
  ['', '16', ' ', 'md-movies', ' ', 'No one under 16 years permitted', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'md-movies', ' ', 'No one under 18 years permitted', ' ', '18', ' ', '18'],
  ['', 'Neclasi', 'fi', 'cat', ' ', 'md-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Neclasi', 'fi', 'cat'],
  [
    '',
    'Mongolia',
    '',
    'General',
    '',
    'Audiences',
    ' ',
    'mn-movies',
    ' ',
    'General audiences',
    ' ',
    'ALL',
    ' ',
    'General Audiences',
  ],
  ['', '13+', ' ', 'mn-movies', ' ', 'For children 13 years of age or over', ' ', '13+', ' ', '13+'],
  ['', '18+', ' ', 'mn-movies', ' ', 'For adults only', ' ', '18+', ' ', '18+'],
  ['', 'Unrated', ' ', 'mn-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'ангилал', ' ', 'тогтоогдоогүй'],
  ['', 'Mozambique', ' ', 'Todas', ' ', 'mz-movies', ' ', 'For all ages', ' ', 'TODAS', ' ', 'Todas'],
  ['', 'M6', ' ', 'mz-movies', ' ', 'For ages 6 and above', ' ', 'M6', ' ', 'M6'],
  ['', 'M12', ' ', 'mz-movies', ' ', 'For ages 12 and above', ' ', 'M12', ' ', 'M12'],
  ['', 'M14', ' ', 'mz-movies', ' ', 'For ages 14 and above', ' ', 'M14', ' ', 'M14'],
  ['', 'M16', ' ', 'mz-movies', ' ', 'For ages 16 and above', ' ', 'M16', ' ', 'M16'],
  ['', 'M18', ' ', 'mz-movies', ' ', 'For ages 18 and above', ' ', 'M18', ' ', 'M18'],
  ['', 'Unrated', ' ', 'mz-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sem Classi', 'fi', 'cação'],
  ['', 'Namibia', ' ', 'A', ' ', 'na-movies', ' ', 'All ages', ' ', 'A', ' ', 'A'],
  [
    '',
    'PG',
    ' ',
    'na-movies',
    '',
    'All ages but parental guidance is recommended for',
    '',
    'younger or sensitive viewers',
    ' ',
    'PG',
    ' ',
    'PG',
  ],
  ['', '10', ' ', 'na-movies', ' ', 'Restricted to persons 10 years and older', ' ', '10', ' ', '10'],
  ['', '13PG', ' ', 'na-movies', ' ', 'Parental guidance is required for children under 13', ' ', '13PG', ' ', '13PG'],
  ['', '13', ' ', 'na-movies', ' ', 'Restricted to persons 13 years and older', ' ', '13', ' ', '13'],
  ['', '16', ' ', 'na-movies', ' ', 'Restricted to persons 16 years and older', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'na-movies', ' ', 'Restricted to adults over 18 years only', ' ', '18', ' ', '18'],
  ['', 'Unrated', ' ', 'na-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Nepal', ' ', 'U', ' ', 'np-movies', ' ', 'Open to general audiences', ' ', 'U', ' ', 'U'],
  ['', 'PG', ' ', 'np-movies', ' ', 'Children under 16 must be accompanied by an adult', ' ', 'PG', ' ', 'PG'],
  ['', 'A', ' ', 'np-movies', ' ', 'Adults only, children under 16 not admitted', ' ', 'A', ' ', 'A'],
  [
    '',
    'R',
    ' ',
    'np-movies',
    ' ',
    'For a person belonging to speci',
    'fi',
    'c profession or',
    ' ',
    'fi',
    'eld',
    ' ',
    'R',
    ' ',
    'R',
  ],
  ['', 'Unrated', ' ', 'np-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Netherlands', ' ', 'AL', ' ', 'nl-movies', ' ', 'Suitable for all ages', ' ', 'AL', ' ', 'AL'],
  ['', 'AL/G', ' ', 'nl-movies', ' ', 'Suitable for all ages', ' ', 'AL-G *', ' ', 'AL/G'],
  ['', '6', ' ', 'nl-movies', ' ', 'Not suitable for viewers under the age of 6', ' ', '6', ' ', '6'],
  ['', '9', ' ', 'nl-movies', ' ', 'Not suitable for viewers under the age of 9', ' ', '9', ' ', '9'],
  ['', '12', ' ', 'nl-movies', ' ', 'Not suitable for viewers under the age of 12', ' ', '12', ' ', '12'],
  ['', '16', ' ', 'nl-movies', ' ', 'Not suitable for viewers under the age of 16', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'nl-movies', ' ', 'Not suitable for viewers under the age of 18', ' ', '18', ' ', '18'],
  [
    '',
    'Niet',
    '',
    'geclassi',
    'fi',
    'ceerd',
    ' ',
    'nl-movies',
    ' ',
    'Unrated',
    ' ',
    'UR',
    ' ',
    'Niet geclassi',
    'fi',
    'ceerd',
  ],
  ['', 'New Zealand', ' ', 'G', ' ', 'nz-o', 'fl', 'c', ' ', 'Anyone can be shown or sold this', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'nz-o', 'fl', 'c', ' ', 'Parental guidance may be needed for younger viewers', ' ', 'PG', ' ', 'PG'],
  ['', 'M', ' ', 'nz-o', 'fl', 'c', ' ', 'More suitable for viewers over 16 years', ' ', 'M', ' ', 'M'],
  [
    '',
    '13',
    ' ',
    'nz-o',
    'fl',
    'c',
    '',
    'Children under the age of 13 must be supervised by a',
    '',
    'parent or guardian',
    ' ',
    '13',
    ' ',
    '13',
  ],
  [
    '',
    '16',
    ' ',
    'nz-o',
    'fl',
    'c',
    '',
    'Children under the age of 16 must be supervised by a',
    '',
    'parent or guardian',
    ' ',
    '16',
    ' ',
    '16',
  ],
  [
    '',
    '18',
    ' ',
    'nz-o',
    'fl',
    'c',
    '',
    'Children under the age of 18 must be supervised by a',
    '',
    'parent or guardian',
    ' ',
    '18',
    ' ',
    '18',
  ],
  [
    '',
    'RP13',
    ' ',
    'nz-o',
    'fl',
    'c',
    '',
    'It is illegal to show this',
    ' ',
    'fi',
    'lm to a person under the age',
    '',
    'of 13 unless they are accompanied by a parent or',
    '',
    'guardian',
    ' ',
    'RP13',
    ' ',
    'RP13',
  ],
  [
    '',
    'R13',
    ' ',
    'nz-o',
    'fl',
    'c',
    '',
    'It is illegal for anyone to show or sell this to someone',
    '',
    'under 13 years of age',
    ' ',
    'R13',
    ' ',
    'R13',
  ],
  [
    '',
    'R15',
    ' ',
    'nz-o',
    'fl',
    'c',
    '',
    'It is illegal for anyone to show or sell this to someone',
    '',
    'under 15 years of age',
    ' ',
    'R15',
    ' ',
    'R15',
  ],
  [
    '',
    'RP16',
    ' ',
    'nz-o',
    'fl',
    'c',
    '',
    'It is illegal to show this',
    ' ',
    'fi',
    'lm to a person under the age',
    '',
    'of 16 unless they are accompanied by a parent or',
    '',
    'guardian',
    ' ',
    'RP16',
    ' ',
    'RP16',
  ],
  [
    '',
    'R16',
    ' ',
    'nz-o',
    'fl',
    'c',
    '',
    'It is illegal for anyone to show or sell this to someone',
    '',
    'under 16 years of age',
    ' ',
    'R16',
    ' ',
    'R16',
  ],
  [
    '',
    'R18',
    ' ',
    'nz-o',
    'fl',
    'c',
    '',
    'It is illegal to show or sell this to someone under 18',
    '',
    'years of age',
    ' ',
    'R18',
    ' ',
    'R18',
  ],
  ['', 'Unrated', ' ', '✓', ' ', 'nz-o', 'fl', 'c', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Nicaragua', ' ', 'TP', ' ', 'ni-movies', ' ', 'All Audiences', ' ', 'TP', ' ', 'TP'],
  ['', 'PG', ' ', 'ni-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  ['', 'PG-13', ' ', 'ni-movies', ' ', 'Viewers older than 13 years', ' ', 'PG-13', ' ', 'PG-13'],
  ['', 'R', ' ', 'ni-movies', ' ', 'Viewers older than 18 years', ' ', 'R', ' ', 'R'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'ni-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  ['', 'Niger', ' ', 'Tout Public', ' ', 'ne-movies', ' ', 'Suitable for all audiences', ' ', 'TP', ' ', 'Tout Public'],
  ['', '12+', ' ', 'ne-movies', ' ', 'Parental guidance 12+', ' ', '12+', ' ', '12+'],
  ['', '15+', ' ', 'ne-movies', ' ', '15+ Mature audiences', ' ', '15+', ' ', '15+'],
  ['', 'Unrated', ' ', 'ne-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Non Classé'],
  ['', 'Nigeria', ' ', 'G', ' ', 'ng-movies', ' ', 'General Exhibition', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'ng-movies', ' ', 'Parental Guidance Suggested', ' ', 'PG', ' ', 'PG'],
  [
    '',
    '12A',
    ' ',
    'ng-movies',
    '',
    'Not suitable for persons less than 12 unless',
    '',
    'accompanied by an adult',
    ' ',
    '12A',
    ' ',
    '12A',
  ],
  ['', '12', ' ', 'ng-movies', ' ', 'Not suitable for persons less than 12', ' ', '12', ' ', '12'],
  ['', '15', ' ', 'ng-movies', ' ', 'Not suitable for persons less than 15', ' ', '15', ' ', '15'],
  [
    '',
    '18',
    ' ',
    'ng-movies',
    '',
    'Not suitable for people under the 18 as the content',
    '',
    'has a high impact',
    ' ',
    '18',
    ' ',
    '18',
  ],
  ['', 'Unrated', ' ', '✓', ' ', 'ng-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Norway', ' ', 'A', ' ', 'no-movies', ' ', 'For all ages', ' ', 'A', ' ', 'A'],
  ['', '6', ' ', 'no-movies', ' ', 'Not for under 6 years of age', ' ', '6', ' ', '6'],
  ['', '9', ' ', 'no-movies', ' ', 'Not for under 9 years of age', ' ', '9', ' ', '9'],
  ['', '12', ' ', 'no-movies', ' ', 'Not for under 12 years of age', ' ', '12', ' ', '12'],
  [
    '',
    '15',
    ' ',
    'no-movies',
    '',
    'Not for under 15 years of age (12 years of age with',
    '',
    'parent)',
    ' ',
    '15',
    ' ',
    '15',
  ],
  ['', '18', ' ', 'no-movies', ' ', 'Not for under 18 years of age', ' ', '18', ' ', '18'],
  ['', 'Oman', ' ', 'U', ' ', 'om-movies', ' ', 'Universal, suitable for all', ' ', 'U', ' ', 'U'],
  ['', 'PG', ' ', 'om-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  ['', '12', ' ', 'om-movies', ' ', 'Suitable for 12 years and older', ' ', '12', ' ', '12'],
  ['', '15', ' ', 'om-movies', ' ', 'Suitable for 15 years and over', ' ', '15', ' ', '15'],
  ['', '18', ' ', 'om-movies', ' ', 'Suitable for 18 years and over', ' ', '18', ' ', '18'],
  ['', 'Unrated', ' ', 'om-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'مصنف', ' ', 'غير'],
  ['', 'Panama', ' ', 'G', ' ', 'pa-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'pa-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'pa-movies',
    '',
    'Parental Guidance; some material may be',
    '',
    'inappropriate for pre-teenagers',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'pa-movies', ' ', 'Restricted', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'pa-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'pa-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  ['', 'A', ' ', 'pa-movies', ' ', 'Todo Público', ' ', 'A', ' ', 'A'],
  ['', 'B', ' ', 'pa-movies', ' ', 'Mayores de 12 años', ' ', 'B', ' ', 'B'],
  ['', 'C', ' ', 'pa-movies', ' ', 'Mayores de 14 años', ' ', 'C', ' ', 'C'],
  ['', 'D', ' ', 'pa-movies', ' ', 'Mayores de 18 años', ' ', 'D', ' ', 'D'],
  ['', 'Papua New Guinea', ' ', 'G', ' ', 'pg-movies', ' ', 'Suitable for general exhibition', ' ', 'G', ' ', 'G'],
  [
    '',
    'PGR',
    ' ',
    'pg-movies',
    '',
    'May be viewed by a person under the age of 18 years',
    '',
    'with the guidance of a parent or Guardian',
    ' ',
    'PGR',
    ' ',
    'PGR',
  ],
  [
    '',
    'MA',
    ' ',
    'pg-movies',
    '',
    'Not recommended for viewing by persons under the',
    '',
    'age of 18 years',
    ' ',
    'MA',
    ' ',
    'MA',
  ],
  [
    '',
    'R',
    ' ',
    'pg-movies',
    '',
    'Likely to cause o',
    'ff',
    'ence to a reasonable adult person;',
    '',
    'or is unsuitable for viewing by a minor',
    ' ',
    'R',
    ' ',
    'R',
  ],
  ['', 'Unrated', ' ', '✓', ' ', 'pg-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Paraguay', ' ', 'ATP', ' ', 'py-movies', ' ', 'All Audiences', ' ', 'ATP', ' ', 'ATP'],
  ['', 'SAM 13', ' ', 'py-movies', ' ', 'Restricted to viewers over 13', ' ', 'SAM13', ' ', 'SAM 13'],
  ['', '15', ' ', 'py-movies', ' ', 'Apta mayores de 15 años', ' ', '15', ' ', '15'],
  ['', 'SAM 16', ' ', 'py-movies', ' ', 'Restricted to viewers over 16', ' ', 'SAM16', ' ', 'SAM 16'],
  ['', 'SAM 18', ' ', 'py-movies', ' ', 'Restricted to viewers over 18', ' ', 'SAM18', ' ', 'SAM 18'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'py-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  ['', 'C', ' ', '✓', ' ', 'py-movies', ' ', 'Restricted to viewers over 18', ' ', 'C', ' ', 'C'],
  ['', 'Peru', ' ', 'APT', ' ', 'pe-movies', ' ', 'All Audiences', ' ', 'APT', ' ', 'APT'],
  ['', '14', ' ', 'pe-movies', ' ', 'For viewers older than 14 years', ' ', '14', ' ', '14'],
  ['', '18', ' ', 'pe-movies', ' ', 'For viewers older than 18 years', ' ', '18', ' ', '18'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'pe-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  [
    '',
    'Philippines',
    ' ',
    'G',
    ' ',
    'ph-movies',
    ' ',
    'General audiences.',
    ' ',
    'All ages admitted',
    ' ',
    'G',
    ' ',
    'G',
  ],
  ['', 'PG', ' ', 'ph-movies', ' ', 'Children under 13 must be accompanied by an adult.', ' ', 'PG', ' ', 'PG'],
  ['', 'R-13', ' ', 'ph-movies', ' ', 'Restricted to 13 years and above', ' ', 'R-13', ' ', 'R-13'],
  ['', 'R-16', ' ', 'ph-movies', ' ', 'Strictly for persons 16 years and over', ' ', 'R-16', ' ', 'R-16'],
  ['', 'R-18', ' ', 'ph-movies', ' ', 'Restricted to 18 years above', ' ', 'R-18', ' ', 'R-18'],
  ['', 'Unrated', ' ', 'ph-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'X', ' ', '✓', ' ', 'ph-movies', ' ', 'Not for public exhibition', ' ', 'X', ' ', 'X'],
  ['', 'Poland', ' ', 'BO', ' ', 'pl-movies', ' ', 'No age limitation or other restrictions', ' ', 'BO *', ' ', 'BO'],
  ['', 'G', ' ', 'pl-movies', ' ', 'No age limitation or other restrictions', ' ', 'G', ' ', 'G'],
  ['', '7', ' ', 'pl-movies', ' ', 'Available for minors over 7', ' ', '7 *', ' ', '7'],
  ['', '12', ' ', 'pl-movies', ' ', 'Available for minors over 12', ' ', '12', ' ', '12'],
  ['', '15', ' ', 'pl-movies', ' ', 'Available for minors over 15', ' ', '15 *', ' ', '15'],
  ['', '16', ' ', 'pl-movies', ' ', 'Available for minors over 16', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'pl-movies', ' ', 'Available only for persons above 18 years old', ' ', '18', ' ', '18'],
  [
    '',
    'Nie Nadano',
    '',
    'Kategorii',
    '',
    'Wiekowej',
    ' ',
    'pl-movies',
    ' ',
    'Unrated',
    ' ',
    'UR *',
    '',
    'Nie Nadano Kategorii',
    '',
    'Wiekowej',
  ],
  ['', 'Portugal', ' ', 'T', ' ', 'pt-movies', ' ', 'Suitable without age restriction', ' ', 'T', ' ', 'T'],
  [
    '',
    'M/3',
    ' ',
    'pt-movies',
    '',
    'Short, easily understood',
    ' ',
    'fi',
    'lms which do not contain',
    '',
    'frightening themes and which are suitable for viewers',
    '',
    'age 3 or over',
    ' ',
    'M3',
    ' ',
    'M/3',
  ],
  [
    '',
    'M/4',
    '',
    'Movies with short duration and easy comprehension',
    '',
    'that do not cause frightening reactions',
    ' ',
    'M4',
    ' ',
    'M/4',
  ],
  ['', 'M/6', ' ', 'pt-movies', ' ', 'All movies not otherwise classi', 'fi', 'ed', ' ', 'M6', ' ', 'M/6'],
  [
    '',
    'M/12',
    ' ',
    'pt-movies',
    '',
    'Movies that, by their extension and complexity, could',
    '',
    'cause fatigue or psychological trauma to younger',
    '',
    'children',
    ' ',
    'M12',
    ' ',
    'M/12',
  ],
  [
    '',
    'M/14',
    ' ',
    'pt-movies',
    '',
    'Films which are suitable for viewers age 14 or over,',
    '',
    'and which might cause anxiety or psychological',
    '',
    'trauma to younger children',
    ' ',
    'M14',
    ' ',
    'M/14',
  ],
  [
    '',
    'M/16',
    ' ',
    'pt-movies',
    '',
    'Movies that explore excessive aspects of sexuality',
    '',
    'and/or violence',
    ' ',
    'M16',
    ' ',
    'M/16',
  ],
  [
    '',
    'M/18',
    ' ',
    '✓',
    ' ',
    'pt-movies',
    '',
    'M/18 - Movies that explore pathological forms of',
    '',
    'physical and/or psychic violence',
    ' ',
    'M18',
    ' ',
    'M/18',
  ],
  [
    '',
    'Sem',
    '',
    'Classi',
    'fi',
    'cação',
    ' ',
    'pt-movies',
    ' ',
    'Unrated',
    ' ',
    'UR',
    ' ',
    'Sem Classi',
    'fi',
    'cação',
  ],
  ['', 'Qatar', ' ', 'G', ' ', 'qa-movies', ' ', 'For general viewing', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'qa-movies', ' ', 'Parental guidance is recommended', ' ', 'PG', ' ', 'PG'],
  ['', 'PG13', ' ', 'qa-movies', ' ', 'Restricted to those aged 13 and above', ' ', 'PG13', ' ', 'PG13'],
  ['', '13', ' ', 'qa-movies', ' ', 'Restricted to those aged 13 and above', ' ', '13 *', ' ', '13'],
  ['', 'PG15', ' ', 'qa-movies', ' ', 'Restricted to those aged 15 and above', ' ', 'PG15', ' ', 'PG15'],
  ['', '15', ' ', 'qa-movies', ' ', 'Restricted to those aged 15 and above', ' ', '15 *', ' ', '15'],
  ['', '15+', ' ', 'qa-movies', ' ', 'Restricted to those aged 15 and above', ' ', '15+', ' ', '15+'],
  ['', '18', ' ', 'qa-movies', ' ', 'Restricted to those aged 18 and above', ' ', '18 *', ' ', '18'],
  ['', '18+', ' ', 'qa-movies', ' ', 'Restricted to those aged 18 and above', ' ', '18+', ' ', '18+'],
  ['', 'Unrated', ' ', 'qa-movies', ' ', 'Unrated', ' ', 'UR *', ' ', 'مصنف', ' ', 'غير'],
  [
    '',
    'Quebec',
    '',
    'Not Rated / Non',
    '',
    'classé',
    ' ',
    'ca-rcq',
    ' ',
    'Not Rated',
    ' ',
    'NR',
    ' ',
    'Not Rated / Non classé',
  ],
  [
    '',
    'G',
    ' ',
    'ca-rcq',
    '',
    'The',
    ' ',
    'fi',
    'lm is appropriate for viewing, rental or purchase',
    '',
    'by persons of all ages',
    ' ',
    'G',
    ' ',
    'G',
  ],
  [
    '',
    '13+',
    ' ',
    'ca-rcq',
    '',
    'The',
    ' ',
    'fi',
    'lm may be viewed, purchased or rented only by',
    '',
    'persons 13 years of age or older',
    ' ',
    '13ç',
    ' ',
    '13+',
  ],
  [
    '',
    '16+',
    ' ',
    'ca-rcq',
    '',
    'The',
    ' ',
    'fi',
    'lm may be viewed, purchased or rented only by',
    '',
    'persons 16 years of age and over',
    ' ',
    '16+',
    ' ',
    '16+',
  ],
  [
    '',
    '18+',
    ' ',
    'ca-rcq',
    '',
    'The',
    ' ',
    'fi',
    'lm may be viewed, purchased or rented only by',
    '',
    'persons 18 years of age and over',
    ' ',
    '18+',
    ' ',
    '18+',
  ],
  ['', 'Unrated / Non', '', 'classé', ' ', 'ca-rcq', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated / Non classé'],
  [
    '',
    'Romania',
    ' ',
    'A.G.',
    ' ',
    'ro-movies',
    ' ',
    'May be viewed by any category of the public',
    ' ',
    'AG',
    ' ',
    'A.G.',
  ],
  [
    '',
    'A.P.-12',
    ' ',
    'ro-movies',
    '',
    'May be viewed by children up to 12 years of age only',
    '',
    'with parental consent',
    ' ',
    'AP-12',
    ' ',
    'A.P.-12',
  ],
  ['', 'N-15', ' ', 'ro-movies', ' ', 'Not recommended for children under 15 years of age', ' ', 'N-15', ' ', 'N-15'],
  [
    '',
    'I.M.-18',
    ' ',
    'ro-movies',
    ' ',
    'Not recommended for children under 18 years of age',
    ' ',
    'IM-18',
    ' ',
    'I.M.-18',
  ],
  ['', 'Neclasi', 'fi', 'cat', ' ', 'ro-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Neclasi', 'fi', 'cat'],
  [
    '',
    '18+',
    ' ',
    'ro-movies',
    '',
    'Not recommended for children under 18;',
    ' ',
    'explicit',
    '',
    'sexual acts or excessive cruelty',
    ' ',
    '18+',
    ' ',
    'I.M.18- XXX',
  ],
  ['', 'Russia', ' ', '0+', ' ', 'ru-movies', ' ', 'For any age audience', ' ', '0', ' ', '0+'],
  ['', '6+', ' ', 'ru-movies', ' ', 'For children older than 6 years', ' ', '6+', ' ', '6+'],
  ['', '12+', ' ', 'ru-movies', ' ', 'For children older than 12 years', ' ', '12', ' ', '12+'],
  ['', '16+', ' ', 'ru-movies', ' ', 'For children older than 16 years', ' ', '16', ' ', '16+'],
  ['', '18+', ' ', 'ru-movies', ' ', 'Prohibited for children', ' ', '18', ' ', '18+'],
  ['', 'Saint Kitts and Nevis', ' ', 'G', ' ', 'kn-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'kn-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'kn-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'kn-movies', ' ', 'Restricted.', ' ', 'Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'kn-movies', ' ', 'No children under 17 admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'kn-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Saudi Arabia', ' ', 'G', ' ', 'sa-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'sa-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG12',
    ' ',
    'sa-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '12 years of age',
    ' ',
    'PG12',
    ' ',
    'PG12',
  ],
  [
    '',
    'PG-13',
    ' ',
    'sa-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13 *',
    ' ',
    'PG-13',
  ],
  ['', 'R12', ' ', 'sa-movies', ' ', 'Restricted. Under 12 requires a parent or guardian', ' ', 'R12', ' ', 'R12'],
  ['', 'R15', ' ', 'sa-movies', ' ', 'Restricted. Under 15 requires a parent or guardian', ' ', 'R15', ' ', 'R15'],
  ['', 'R18', ' ', 'sa-movies', ' ', 'Restricted. Under 18 requires a parent or guardian', ' ', 'R18', ' ', 'R18'],
  ['', 'R', ' ', 'sa-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R *', ' ', 'R'],
  ['', 'NC-17', ' ', 'sa-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17 *', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'sa-movies', ' ', 'Unrated', ' ', 'UR *', ' ', 'مصنف', ' ', 'غير'],
  ['', 'Singapore', ' ', 'G', ' ', 'sg-movies', ' ', 'General. Suitable for all ages', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'sg-movies', ' ', 'Parental guidance', ' ', 'PG', ' ', 'PG'],
  ['', 'PG-13', ' ', 'sg-movies', ' ', 'Parental guidance suggested for children under 13', ' ', 'PG-13', ' ', 'PG-13'],
  ['', 'NC16', ' ', 'sg-movies', ' ', 'No children below 16 years', ' ', 'NC16', ' ', 'NC16'],
  ['', 'M18', ' ', 'sg-movies', ' ', 'Mature 18.', ' ', 'For 18 years and above', ' ', 'M18', ' ', 'M18'],
  ['', 'R21', ' ', '✓', ' ', 'sg-movies', ' ', 'Restricted: no one under 21 admitted', ' ', 'R21 *', ' ', 'R21'],
  ['', 'Slovakia', ' ', 'U', ' ', 'sk-movies', ' ', 'Appropriate for all age groups of minors', ' ', 'U', ' ', 'U'],
  ['', '7', ' ', 'sk-movies', ' ', 'Inappropriate for minors under the age of 7', ' ', '7', ' ', '7'],
  ['', '12', ' ', 'sk-movies', ' ', 'Inappropriate for minors under the age of 12', ' ', '12', ' ', '12'],
  ['', '15', ' ', 'sk-movies', ' ', 'Inappropriate for minors under the age of 15', ' ', '15', ' ', '15'],
  ['', '18', ' ', 'sk-movies', ' ', 'Inappropriate for minors under the age of 18', ' ', '18', ' ', '18'],
  ['', 'Unrated', ' ', '✓', ' ', 'sk-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Slovenia', ' ', 'VS', ' ', 'si-movies', ' ', 'Suitable for children', ' ', 'VS', ' ', 'VS'],
  ['', '12', ' ', 'si-movies', ' ', 'Suitable for children over 12 years of age', ' ', '12', ' ', '12'],
  ['', '15', ' ', 'si-movies', ' ', 'Suitable only for adolescents over the age of 15', ' ', '15', ' ', '15'],
  ['', '18', ' ', 'si-movies', ' ', 'Suitable only for adults 18 years and above', ' ', '18', ' ', '18'],
  ['', 'AD', ' ', 'si-movies', ' ', 'Suitable for adults only', ' ', 'AD', ' ', 'AD'],
  ['', 'Unrated', ' ', '✓', ' ', 'si-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'South Africa', ' ', 'A', ' ', 'za-movies', ' ', 'All ages', ' ', 'A', ' ', 'A'],
  [
    '',
    'PG',
    ' ',
    'za-movies',
    '',
    'All ages but parental guidance is recommended for',
    '',
    'younger or sensitive viewers',
    ' ',
    'PG',
    ' ',
    'PG',
  ],
  [
    '',
    '7-9PG',
    ' ',
    'za-movies',
    '',
    'Restricted to persons 7 years and older. Children',
    '',
    'between the ages of 7 and 9 should be accompanied',
    '',
    'by an adult',
    ' ',
    '7-9PG',
    ' ',
    '7-9PG',
  ],
  ['', '10', ' ', 'za-movies', ' ', 'Restricted to persons 10 years and older', ' ', '10 *', ' ', '10'],
  [
    '',
    '10-12PG',
    ' ',
    'za-movies',
    '',
    'Restricted to persons 10 years and older. Children',
    '',
    'between the ages of 10 and 12 should be',
    '',
    'accompanied by an adult',
    ' ',
    '10-12PG',
    ' ',
    '10-12PG',
  ],
  ['', '13', ' ', 'za-movies', ' ', 'Restricted to persons 13 years and older', ' ', '13', ' ', '13'],
  ['', '16', ' ', 'za-movies', ' ', 'Restricted to persons 16 years and older', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'za-movies', ' ', 'Restricted to adults over 18 years only', ' ', '18', ' ', '18'],
  [
    '',
    'X18',
    ' ',
    '✓',
    ' ',
    'za-movies',
    '',
    'Restricted to adults over 18 years only; hardcore',
    '',
    'pornography',
    ' ',
    'X18 *',
    ' ',
    'X18',
  ],
  ['', 'Unrated', ' ', '✓', ' ', 'za-movies', ' ', 'Unrated', ' ', 'UR *', ' ', 'Unrated'],
  ['', 'Spain', ' ', 'iA', ' ', 'es-movies', ' ', 'Especially recommended for children', ' ', 'IA', ' ', 'iA'],
  [
    '',
    'i7',
    ' ',
    'es-movies',
    '',
    'Especially recommended for children. Not',
    '',
    'recommended for children under 7 years',
    ' ',
    'I7',
    ' ',
    'i7',
  ],
  ['', 'A/TP', ' ', 'es-movies', ' ', 'For all the public', ' ', 'A-TP', ' ', 'A/TP'],
  ['', '7', ' ', 'es-movies', ' ', 'Not recommended for children under 7 years', ' ', '7', ' ', '7'],
  ['', '12', ' ', 'es-movies', ' ', 'Not recommended for children under 12 years', ' ', '12', ' ', '12'],
  ['', '13', ' ', 'es-movies', ' ', 'Not recommended for children under 13 years', ' ', '13 *', ' ', '13'],
  ['', '15', ' ', 'es-movies', ' ', 'Not recommended for children under 15 years', ' ', '15', ' ', '15'],
  ['', '16', ' ', 'es-movies', ' ', 'Not recommended for children under 16 years', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'es-movies', ' ', 'Not recommended for children under 18 years', ' ', '18', ' ', '18'],
  ['', 'Unrated', ' ', '✓', ' ', 'es-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Sri Lanka', ' ', 'U', ' ', 'lk-movies', ' ', 'For unlimited exhibition', ' ', 'U', ' ', 'U'],
  ['', 'A', ' ', 'lk-movies', ' ', 'More suitable for adults', ' ', 'A', ' ', 'A'],
  ['', 'X', ' ', '✓', ' ', 'lk-movies', ' ', 'Adults only', ' ', 'X', ' ', 'X'],
  ['', 'Unrated', ' ', 'lk-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  [
    '',
    'Sweden',
    ' ',
    'Barntillåten',
    ' ',
    'se-movies',
    ' ',
    'Universal/permissible for children',
    ' ',
    'ALL',
    ' ',
    'Barntillåten',
  ],
  ['', 'Från 7 år', ' ', 'se-movies', ' ', 'From 7 years', ' ', '7+', ' ', 'Från 7 år'],
  ['', 'Från 11 år', ' ', 'se-movies', ' ', 'From 11 years', ' ', '11+', ' ', 'Från 11 år'],
  ['', 'Från 15 år', ' ', 'se-movies', ' ', 'From 15 years', ' ', '15+', ' ', 'Från 15 år'],
  ['', 'Inte klassi', 'fi', 'cerad', ' ', 'se-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Inte klassi', 'fi', 'cerad'],
  ['', 'Switzerland', ' ', '0', ' ', 'ch-movies', ' ', 'For all ages', ' ', '0', ' ', '0'],
  ['', '6', ' ', 'ch-movies', ' ', 'Not for under 6 years of age', ' ', '6', ' ', '6'],
  ['', '7', ' ', 'ch-movies', ' ', 'Not for under 7 years of age', ' ', '7 *', ' ', '7'],
  ['', '8', ' ', 'ch-movies', ' ', 'Not for under 8 years of age', ' ', '8', ' ', '8'],
  ['', '10', ' ', 'ch-movies', ' ', 'Not for under 10 years of age', ' ', '10', ' ', '10'],
  ['', '12', ' ', 'ch-movies', ' ', 'Not for under 12 years of age', ' ', '12', ' ', '12'],
  ['', '14', ' ', 'ch-movies', ' ', 'Not for under 14 years of age', ' ', '14', ' ', '14'],
  ['', '16', ' ', 'ch-movies', ' ', 'Not for under 16 years of age', ' ', '16', ' ', '16'],
  ['', '18', ' ', 'ch-movies', ' ', 'Not for under 18 years of age', ' ', '18', ' ', '18'],
  ['', 'Keine', '', 'Alterseinstufung', ' ', 'ch-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Keine Alterseinstufung'],
  [
    '',
    'Taiwan',
    ' ',
    '普遍級',
    ' ',
    'tw-movies',
    ' ',
    'General audiences. Permitted for audiences of all ages',
    ' ',
    'ALL',
    ' ',
    '普遍級',
  ],
  [
    '',
    '保護級',
    ' ',
    'tw-movies',
    '',
    'Protected.',
    ' ',
    'Not permitted for children under age 6;',
    '',
    'children between ages 6 and 12 must be under',
    '',
    'guidance',
    ' ',
    '6',
    ' ',
    '保護級',
  ],
  [
    '',
    '輔',
    '12',
    '級',
    ' ',
    'tw-movies',
    ' ',
    'Not permitted for children under 12',
    ' ',
    '12',
    ' ',
    '輔',
    '12',
    '級',
  ],
  [
    '',
    '輔',
    '15',
    '級',
    ' ',
    'tw-movies',
    ' ',
    'Suitable for persons aged 15 and above',
    ' ',
    '15',
    ' ',
    '輔',
    '15',
    '級',
  ],
  ['', '限制級', ' ', 'tw-movies', ' ', 'Restricted. Not permitted for those under 18', ' ', '18', ' ', '限制級'],
  ['', '未經分級', ' ', 'tw-movies', ' ', 'Unrated', ' ', 'UR', ' ', '未經分級'],
  ['', 'Tajikistan', ' ', 'A', ' ', 'tj-movies', ' ', 'General audiences (all ages)', ' ', 'A', ' ', 'A'],
  ['', '7+', ' ', 'tj-movies', ' ', 'Audiences age 7 and above', ' ', '7+', ' ', 'Б', '-7'],
  [
    '',
    'T',
    ' ',
    'tj-movies',
    '',
    'Children under 16 only allowed to view in the',
    '',
    'company of a parent or guardian',
    ' ',
    'T',
    ' ',
    'Т',
  ],
  ['', '16+', ' ', 'tj-movies', ' ', 'For audiences age 16 and above', ' ', '16+', ' ', 'Б', '-16'],
  ['', '18+', ' ', 'tj-movies', ' ', 'Only for audiences age 18 and above', ' ', '18+', ' ', 'Ш'],
  ['', 'UR', ' ', 'tj-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Без', ' ', 'классификации'],
  [
    '',
    'Thailand',
    ' ',
    'ส',
    ' ',
    'ส่',
    ' ',
    'งเส',
    'ริ',
    ' ',
    'ม',
    ' ',
    'th-movies',
    ' ',
    'Supports learning and should be promoted',
    ' ',
    'EDU',
    ' ',
    'ส',
    ' ',
    'ส่',
    ' ',
    'งเส',
    'ริ',
    ' ',
    'ม',
  ],
  [
    '',
    'ท',
    ' ',
    'ทั่',
    ' ',
    'วไป',
    ' ',
    'th-movies',
    ' ',
    'Suitable for all viewers',
    ' ',
    'ALL',
    ' ',
    'ท',
    ' ',
    'ทั่',
    ' ',
    'วไป',
  ],
  ['', 'น', ' ', '13+', ' ', 'th-movies', ' ', 'Suitable for persons 13 and above', ' ', '13+', ' ', 'น', ' ', '13+'],
  [
    '',
    'น',
    ' ',
    '15+',
    ' ',
    'th-movies',
    ' ',
    'Suitable for persons 15 years and above',
    ' ',
    '15+',
    ' ',
    'น',
    ' ',
    '15+',
  ],
  [
    '',
    'น',
    ' ',
    '18+',
    ' ',
    'th-movies',
    ' ',
    'Suitable for persons 18 years and above',
    ' ',
    '18+',
    ' ',
    'น',
    ' ',
    '18+',
  ],
  [
    '',
    'ไ',
    'ม่',
    ' ',
    'ไ',
    'ด้',
    ' ',
    'จั',
    ' ',
    'ด',
    'อั',
    ' ',
    'น',
    'ดั',
    ' ',
    'บ',
    ' ',
    'th-movies',
    ' ',
    'Unrated',
    ' ',
    'UR',
    ' ',
    'ไ',
    'ม่',
    ' ',
    'ไ',
    'ด้',
    ' ',
    'จั',
    ' ',
    'ด',
    'อั',
    ' ',
    'น',
    'ดั',
    ' ',
    'บ',
  ],
  ['', '20+', ' ', '✓', ' ', 'th-movies', ' ', 'Film not suitable for viewers under 20', ' ', '20+', ' ', '20+'],
  [
    '',
    'Trinidad and Tobago',
    ' ',
    'All Ages',
    ' ',
    'tt-movies',
    ' ',
    'Open to general audiences',
    ' ',
    'ALL',
    ' ',
    'All Ages',
  ],
  [
    '',
    'All Ages PG',
    ' ',
    'tt-movies',
    '',
    'Open to general audiences but parental guidance',
    '',
    'recommended',
    ' ',
    'PG',
    ' ',
    'All Ages PG',
  ],
  ['', 'PG-13', ' ', 'tt-movies', ' ', 'Recommended for ages over 13', ' ', 'PG-13', ' ', 'PG-13'],
  ['', '14+', ' ', 'tt-movies', ' ', 'No one under 14 years old admitted', ' ', '14+', ' ', '14+'],
  ['', '16+', ' ', 'tt-movies', ' ', 'No one under 16 years old admitted', ' ', '16+', ' ', '16+'],
  ['', '18+', ' ', 'tt-movies', ' ', 'No one under 18 years old admitted', ' ', '18+', ' ', '18+'],
  ['', 'Unrated', ' ', 'tt-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  [
    '',
    'Turkey',
    ' ',
    'Genel',
    ' ',
    'İ',
    'zleyici',
    ' ',
    'tr-movies',
    ' ',
    'General Audiences',
    ' ',
    'ALL',
    ' ',
    'Genel',
    ' ',
    'İ',
    'zleyici',
  ],
  ['', '7+', ' ', 'tr-movies', ' ', 'Appropriate for age 7 and above', ' ', '7+', ' ', '7+'],
  [
    '',
    '7A',
    ' ',
    'tr-movies',
    '',
    'Appropriate for ages below 7 only in the presence of',
    '',
    'their family',
    ' ',
    '7A',
    ' ',
    '7A',
  ],
  ['', '13+', ' ', 'tr-movies', ' ', 'Appropriate for age 13 and above', ' ', '13+', ' ', '13+'],
  [
    '',
    '13A',
    ' ',
    'tr-movies',
    '',
    'Appropriate for ages below 13 only in the presence of',
    '',
    'their family',
    ' ',
    '13A',
    ' ',
    '13A',
  ],
  ['', '15+', ' ', 'tr-movies', ' ', 'Appropriate for age 15 and above', ' ', '15+', ' ', '15+'],
  [
    '',
    '15A',
    ' ',
    'tr-movies',
    '',
    'Appropriate for ages below 15 only in the presence of',
    '',
    'their family',
    ' ',
    '15A',
    ' ',
    '15A',
  ],
  ['', '18+', ' ', 'tr-movies', ' ', 'Appropriate for age 18 and above', ' ', '18+', ' ', '18+'],
  ['', 'Turkmenistan', ' ', 'G', ' ', 'tm-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'tm-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'tm-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'tm-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'tm-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'tm-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Без', ' ', 'классификации'],
  ['', 'Uganda', ' ', 'G', ' ', 'ug-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'ug-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'ug-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'ug-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'ug-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Ukraine', ' ', '0+', ' ', 'ua-movies', ' ', 'Suitable without age restriction', ' ', '0', ' ', '0+'],
  ['', '12+', ' ', 'ua-movies', ' ', 'Suitable for person aged 12 and above', ' ', '12', ' ', '12+'],
  ['', '16+', ' ', 'ua-movies', ' ', 'Suitable for persons aged 16 and above', ' ', '16', ' ', '16+'],
  ['', '18+', ' ', 'ua-movies', ' ', 'Suitable for persons aged 18 and above', ' ', '18', ' ', '18+'],
  [
    '',
    'не',
    ' ',
    'має',
    ' ',
    'індексу',
    '',
    'фільму',
    ' ',
    'ua-movies',
    ' ',
    'Unrated',
    ' ',
    'UR',
    ' ',
    'не',
    ' ',
    'має',
    ' ',
    'індексу',
    ' ',
    'фільму',
  ],
  ['', 'X21', ' ', '✓', ' ', 'ua-movies', ' ', 'No one under 21', ' ', 'is permitted', ' ', 'X21 *', ' ', 'X21'],
  ['', 'United Arab Emirates', ' ', 'G', ' ', 'ae-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  [
    '',
    'PG-13',
    ' ',
    'ae-movies',
    '',
    'Permitted for children under the age of 13 with',
    '',
    'parental supervision or the supervision of individuals',
    '',
    'older than the age of 13',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  [
    '',
    'PG-15',
    ' ',
    'ae-movies',
    '',
    'Permitted for children under the age of 15 with',
    '',
    'parental supervision or the supervision of individuals',
    '',
    'older than the age of 15',
    ' ',
    'PG-15',
    ' ',
    'PG-15',
  ],
  [
    '',
    '15',
    ' ',
    'ae-movies',
    '',
    'Not permitted for children/individuals under the age',
    '',
    'of 15',
    ' ',
    '15',
    ' ',
    '15',
  ],
  [
    '',
    '18',
    ' ',
    'ae-movies',
    '',
    'Not permitted for children/individuals under the age',
    '',
    'of 18',
    ' ',
    '18',
    ' ',
    '18',
  ],
  ['', 'Unrated', ' ', 'ae-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'مصنف', ' ', 'غير'],
  ['', 'United Kingdom', ' ', 'U', ' ', 'bbfc', ' ', 'Suitable for all ages', ' ', 'U', ' ', 'U'],
  ['', 'PG', ' ', 'bbfc', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  ['', '12', ' ', 'bbfc', ' ', 'Suitable for 12 years and over', ' ', '12', ' ', '12'],
  ['', '15', ' ', 'bbfc', ' ', 'Suitable for 15 years and over', ' ', '15', ' ', '15'],
  ['', '18', ' ', 'bbfc', ' ', 'Suitable only for adults', ' ', '18', ' ', '18'],
  [
    '',
    '18R',
    ' ',
    '✓',
    ' ',
    'bbfc',
    '',
    'To be shown only in specially licensed cinemas and to',
    '',
    'adults over 18 years',
    ' ',
    '18R *',
    ' ',
    'R18',
  ],
  ['', 'Unrated', ' ', 'bbfc', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'United States', ' ', 'NR', ' ', 'mpaa', ' ', 'Not Rated', ' ', 'NR', ' ', 'NR'],
  ['', 'G', ' ', 'mpaa', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'mpaa', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'mpaa',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'mpaa', ' ', 'Restricted.', ' ', 'Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', '✓', ' ', 'mpaa', ' ', 'No children under 17 admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'mpaa', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
  ['', 'Uruguay', ' ', 'TP', ' ', 'uy-movies', ' ', 'All Audiences', ' ', 'TP', ' ', 'TP'],
  ['', '6', ' ', 'uy-movies', ' ', 'Viewers older than 6 years', ' ', '6', ' ', '6'],
  ['', '9', ' ', 'uy-movies', ' ', 'Viewers older than 9 years', ' ', '9', ' ', '9'],
  ['', '12', ' ', 'uy-movies', ' ', 'Viewers older than 12 years', ' ', '12', ' ', '12'],
  ['', '15', ' ', 'uy-movies', ' ', 'Viewers older than 15 years', ' ', '15', ' ', '15'],
  ['', '18', ' ', 'uy-movies', ' ', 'Viewers older than 18 years', ' ', '18', ' ', '18'],
  ['', 'Sin Cali', 'fi', 'cación', ' ', 'uy-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Sin Cali', 'fi', 'cación'],
  ['', 'Uzbekistan', ' ', 'G', ' ', 'uz-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'uz-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'uz-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'uz-movies', ' ', 'Restricted.', ' ', 'Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'uz-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'uz-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Без', ' ', 'классификации'],
  ['', 'Venezuela', ' ', 'AA', ' ', 've-movies', ' ', 'Especially for children', ' ', 'AA', ' ', 'AA'],
  ['', 'A', ' ', 've-movies', ' ', 'All Audiences', ' ', 'A', ' ', 'A'],
  ['', 'B', ' ', 've-movies', ' ', 'Viewers older than 12 years', ' ', 'B', ' ', 'B'],
  ['', 'C', ' ', 've-movies', ' ', 'Viewers older than 16 years', ' ', 'C', ' ', 'C'],
  ['', 'D', ' ', 've-movies', ' ', 'Viewers older than 18 years', ' ', 'D', ' ', 'D'],
  [
    '',
    'Sin Cali',
    'fi',
    'cación',
    ' ',
    '✓',
    ' ',
    've-movies',
    ' ',
    'Unrated',
    ' ',
    'UR',
    ' ',
    'Sin Cali',
    'fi',
    'cación',
  ],
  ['', 'Vietnam', ' ', 'P', ' ', 'vn-movies', ' ', 'Suitable for general viewing', ' ', 'P', ' ', 'P'],
  ['', 'C13', ' ', 'vn-movies', ' ', 'Not suitable for viewers under 13', ' ', 'C13', ' ', 'C13'],
  ['', 'C16', ' ', 'vn-movies', ' ', 'Restricted to customers 16 years or older', ' ', 'C16', ' ', 'C16'],
  ['', 'C18', ' ', 'vn-movies', ' ', 'Not suitable for viewers under 18', ' ', 'C18', ' ', 'C18'],
  [
    '',
    'Không c',
    'ắ',
    't c',
    'ả',
    'nh',
    ' ',
    'vn-movies',
    ' ',
    'Unrated',
    ' ',
    'UR *',
    ' ',
    'Không c',
    'ắ',
    't c',
    'ả',
    'nh',
  ],
  ['', 'Zimbabwe', ' ', 'G', ' ', 'zw-movies', ' ', 'General Audiences', ' ', 'G', ' ', 'G'],
  ['', 'PG', ' ', 'zw-movies', ' ', 'Parental Guidance', ' ', 'PG', ' ', 'PG'],
  [
    '',
    'PG-13',
    ' ',
    'zw-movies',
    '',
    'Parental Guidance strongly recommended for under',
    '',
    '13 years of age',
    ' ',
    'PG-13',
    ' ',
    'PG-13',
  ],
  ['', 'R', ' ', 'zw-movies', ' ', 'Restricted. Under 17 requires a parent or guardian', ' ', 'R', ' ', 'R'],
  ['', 'NC-17', ' ', 'zw-movies', ' ', 'Adult. Children under 17 not admitted', ' ', 'NC-17', ' ', 'NC-17'],
  ['', 'Unrated', ' ', 'zw-movies', ' ', 'Unrated', ' ', 'UR', ' ', 'Unrated'],
];
